### ISSUE TITLE
NTR: PME miniPAR Logger

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/L22#101]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Precision Measurement Engineering

## Device range
n/a

## Device model
miniPAR Logger

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
submersible Photosynthetically Active Radiation instrument

## Instrument type
submersible data logger

## Does the tool describe a series of instruments? 
no

## Reference (if applicable)
n/a

## Short name
PME miniPAR Logger

## Documentation
https://www.pme.com/wp-content/uploads/2017/06/miniPAR-logger-pme.pdf
https://www.pme.com/products/minipar-logger

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-9081-1004

**Comment by roswri** [comment]
Hi @whshannon ,

Your new term is now published on the NVS:
Precision Measurement Engineering miniPAR (submersible) data logger
http://vocab.nerc.ac.uk/collection/L22/current/TOOL1784/

Best wishes,
Roseanna

**Comment by whshannon** [comment]
Thank you!
