### ISSUE TITLE
NTR: LI-COR LI-200R Pyranometer (BODCNVS-1691)

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/L22#104]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
LI-COR

## Device range
n/a

## Device model
LI-200R

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a
## Qualification (if applicable)
n/a

## Instrument type
Pyranometer

## Does the tool describe a series of instruments? 
No

## Short name
LI-COR LI-200R

## Documentation
https://www.licor.com/env/products/light/pyranometer.html

## ORCID (optional)
0000-0002-9081-1004

**Comment by SLBlakeman** [comment]
The L22 term for this instrument is:

TOOL1770	LI-COR LI-200R pyranometer (https://vocab.nerc.ac.uk/collection/L22/current/TOOL1770/)
