### ISSUE TITLE
NTR: Vemco VR2Tx Receiver and Transmitter

### ISSUE THREAD

**Issue by danagerl** [nvs-vocabs/L22#108]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Vemco

## Device range
n/a

## Device model
VR2Tx

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
submersible, single-channel acoustic receiver with transmission capabilities

## Instrument type
Acoustic receiver and transmitter;
Telemetry Equipment Device

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
Vemco VR2Tx

## Documentation
[://www.oceans-research.com/wp-content/uploads/2016/09/vr2tx-manual.pdf)](http://www.oceans-research.com/wp-content/uploads/2016/09/vr2tx-manual.pdf)

## Mapping to external terminologies (optional)
(http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C50211)

## ORCID (optional)
0000-0003-3781-4641

**Comment by danibodc** [comment]
This term has now been created:
TOOL1788	Vemco VR2Tx receiver and transmitter

It will be live on the NVS from next week at:
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1788/
