### ISSUE TITLE
NTR: SeaBird SeaOwl UV-A

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#109]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
SeaBird

## Device range
n/a

## Device model
SeaOwl

## Model version
UV-A

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
flurometer

## Does the tool describe a series of instruments? 
no

## Reference (if applicable)
n/a

## Short name
SeaOwl UV-A

## Documentation
https://www.seabird.com/seaowl-uv-a-sea-oil-in-water-locator/product?id=60762467737

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by danibodc** [comment]
This term has now been loaded to L22:

**Code:** TOOL1766	
**Preferred label:** Sea-Bird Scientific {WET Labs} SeaOWL UV-A Sea Oil-in-Water Locator	
**Description:** An optical backscattering sensor measuring chlorophyll, backscattering and Fluorescent Dissolved Organic Matter (FDOM). It uses the same UV-A excitation and blue emission wavelengths currently used in the WET Labs ECO FDOM fluorometer. It is optimised for measuring crude oil in seawater. The chlorophyll fluorescence and backscattering measurements enable discrimination of crude oil from phytoplankton and other natural sources of FDOM. The SeaOWL UV-A improves the resolution and range of the ECO with a greater depth of field, optimised electronics and dynamic gain stage modulation, providing high sensitivity across a large detection range. The SeaOWL UV-A measures backscatter at 700 nm with a sensitivity of 1E-06 m-1 sr -1, over a range of 0-0.04 m-1 sr -1. Chlorophyll fluorescence is measured at 470 EX/890 EM nm with a sensitivity of 0.005 ug/l, over a range of 0.005 - 250 ug/l. FDOM is measured at 370 EX/460 EM nm with a sensitivity of 0.03 ppb QSDE, over a range of 0.03 - 900 ppb QSDE. The limit of oil detection is < 80 ppb at a sensitivity of 3 ppb. The instrument is depth-rated to 2000 m.

It will be live on the NVS from tomorrow morning from 0730 UTC at:
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1766/
