### ISSUE TITLE
NTR: LISST-ABS

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#110]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Sequoia

## Device range
n/a

## Device model
LISST

## Model version
ABS

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
acoustic backscatter

## Does the tool describe a series of instruments? 
no

## Reference (if applicable)
n/a

## Short name
LISST-ABS

## Documentation
https://www.sequoiasci.com/product/lisst-abs/

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by louatbodc** [comment]
A new term has been published for this instrument.

TOOL1800 - Sequoia LISST ABS acoustic backscatter sensor

Please be aware that it may take up to 24 hours for the new term to appear on our web services.
