### ISSUE TITLE
NTR: JFE Rinko ARO-FT

### ISSUE THREAD

**Issue by mcuthill** [nvs-vocabs/L22#111]
## Device make
JFE Advantech

## Device range
Rinko FT

## Device model
ARO-FT

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
oxygen sensor

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
JFE Rinko ARO-FT

## Documentation
https://www.jfe-advantech.co.jp/eng/assets/img/products/ocean-rinko/RINKO_FT(E)_201704.pdf 

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
n/a

**Comment by roswri** [comment]
Hi @mcuthill ,

This term has now been published on the NVS:
JFE Advantech Rinko FT ARO-FT oxygen sensor
http://vocab.nerc.ac.uk/collection/L22/current/TOOL1783/

Best wishes,
Roseanna
