### ISSUE TITLE
NTR: Kongsberg EM 124

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#112]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Kongsberg

## Device range
EM

## Device model
EM 124

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
multibeam

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
EM 124

## Documentation
https://www.kongsberg.com/maritime/products/ocean-science/mapping-systems/multibeam-echo-sounders/em-124-multibeam-echosounder-max.-11000-m/#technicalInformation

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
Hi @rhudak2020,

Your new term is now live on the NVS: http://vocab.nerc.ac.uk/collection/L22/current/TOOL1799/

Please let me know if there are any issues.

Best wishes,
Roseanna
