### ISSUE TITLE
NTR: New device, Campbell Scientific CR3000 Micrologger (BODCNVS-1692)

### ISSUE THREAD

**Issue by s10tagarro** [nvs-vocabs/L22#113]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Campbell Scientific

## Device range
data logger

## Device model
CR

## Model version
3000

## Instrument type
data logger

## Does the tool describe a series of instruments? 
individual

## Short name
CR3000 Micrologger

## Documentation
http://data.utm.csic.es/lib/sensorml/documentation/b_cr3000.pdf

**Comment by SLBlakeman** [comment]
New term has been created and is available on the NVS:
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1922/
TOOL1922 - Campbell Scientific CR3000 data logger
