### ISSUE TITLE
NTR: Setra 278 (BODCNVS-1693)

### ISSUE THREAD

**Issue by s10tagarro** [nvs-vocabs/L22#114]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Setra

## Device range
n/a

## Device model
278

## Model version
n/a

## Instrument type
Barometric Pressure Transducer

## Does the tool describe a series of instruments? 
individual

## Short name
Setra 278

## Documentation
http://data.utm.csic.es/lib/sensorml/documentation/Setra_Model_278_Data_Sheet.pdf

**Comment by JordanAthertonNOC** [comment]
Dear @s10tagarro 

Thanks for your interest in the L22 vocabulary and apologies for the delay in addressing this - it was regrettably missed from our internal tracking procedure. One new L22 term has now been created for the Setra 278 barometer, and this will go live on the NVS after ~08:30 CEST tomorrow. 

Setra 278 barometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1923/)

Best

Jordan
