### ISSUE TITLE
NTR: SeaBeam 1050D

### ISSUE THREAD

**Issue by utmdata** [nvs-vocabs/L22#117]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
L-3 Communications Elac Nautik

## Device range
n/a

## Device model
SeaBeam 1050D

## Model version
n/a

## Instrument type
multibeam echo sounder

## Does the tool describe a series of instruments? 
individual

## Documentation
http://data.utm.csic.es/lib/sensorml/documentation/SeaBeam_1050D.pdf

**Comment by JordanAthertonNOC** [comment]
Dear @utmdata 

Thank you for your request and for your interest in the NVS. A new term has now been created for this instrument and will be live on the NVS overnight:

L-3 Communications SeaBeam 1050D multibeam echosounder (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1798/)

Best

Jordan
