### ISSUE TITLE
NTR: hard substrate suction sampler

### ISSUE THREAD

**Issue by geo-sar** [nvs-vocabs/L22#124]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Hellenic Centre for Marine Research - IMBBC
[This is the name of the manufacturer or institution which made the instrument. If there is a manufacturer but you have not been able to confirm this information or there is no official manufacturer, input 'Inapplicable'. If you are creating a generic instrument (e.g. a generic temperature sensor, then input 'Unspecified'.]

## hard bottom sampler
[The manufacturer's instrument model range (e.g. WindObserver). If there is no official model range then input 'n/a'.]

## manually operated suction sampler for hard bottom benthos
[Name of the instrument model. If there is no official model name, input 'n/a'.]

## n/a
[Name of the sub-model (e.g. 'D', 'v3.2'). If there is no official version/sub-model then input 'n/a'.]

##  MANOSS
[Alternative name for the model. E.g. Glider Payload CTD alternative name is GPCTD]

## n/a
[Describes any modifications to the instrument design, such as a manufactured device that has been modified 'in-house' or a plakton net that has been modified since its first description.]

## Qualification (if applicable)
[Qualification of the instrument type i.e. a word or words that further describe the instrument type (e.g. 'portable','automated','pressure-compensated','large' etc.). Sometimes these are used in manufacturer names.]

## suction sampler
[Please indicate what type of instrument it is (e.g. global positioning system, fluorometer, etc.)]

## individual instrument
[Does the term describe a manufacturing 'series' of instruments, a 'system' of instruments, an 'individual' instrument or other?]

## Chatzigeorgiou, G., Dailianis, T., Faulwetter, S., Pettas, M., & Arvanitidis, C. (2013). MANOSS-a manually operated suction sampler for hard bottom benthos. Transitional Waters Bulletin, 6(2), 42-49.
[Citation for the instrument (e.g. Hall and Bumpus 1937, 1944). Use if the instrument is manufactuered and built according to a design in a paper.]

## MANOSS
[Shortened name of the instrument. This is usually a shortened version of name limited to make, model and version. It can also be an alternative name.]

## http://siba-ese.unisalento.it/index.php/twb/article/view/12799
[Please enter a link to the documentation describing the instrument. This could be a journal reference, manufacturer data sheet, web site, manual etc.]

## http://vocab.nerc.ac.uk/collection/L05/current/24/
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by roswri** [comment]
Hi @geo-sar ,

The new terms has now been created: Hellenic Centre for Marine Research - IMBBC manually operated suction sampler for hard bottom benthos - Chatzigeorgiou, G., Dailianis, T., Faulwetter, S., Pettas, M., & Arvanitidis, C. (2013) (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1815/)

This has been queued for publication but is not yet live on the NVS, it should be live soon.

Best wishes,
Roseanna
