### ISSUE TITLE
NTR: OnSET HOBO Dissolved Oxygen Loggers Model U26-001

### ISSUE THREAD

**Issue by sauuyer** [nvs-vocabs/L22#128]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Onset

## Device range
HOBO

## Device model
U26-001

## Model version
n/a

## Model alternative name (if applicable)
HOBO U26 Data Logger

## Modification (if applicable)
n/a

## Qualification (if applicable)
'optical'

## Instrument type
Optical dissolved o2 sensor

## Does the tool describe a series of instruments? 
n/a

## Reference (if applicable)
n/a

## Short name
HOBO U26 Data Logger

## Documentation
https://www.onsetcomp.com/products/data-loggers/u26-001?creative=586887936925&keyword=dissolved%20oxygen%20logger&matchtype=p&network=g&device=c&gclid=Cj0KCQjwhLKUBhDiARIsAMaTLnEyAVBiYrJ7qHrrLQqzxBWVwQ3D0l5HW9b9b1PMksVdoTnHeHdvXVoaAqQWEALw_wcB

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
0000-0003-3583-7284

**Comment by SLBlakeman** [comment]
Hello @sauuyer 

One new L22 code has now been created, the below link will resolve overnight and should be live on the NVS at ~07:00 BST tomorrow:

https://vocab.nerc.ac.uk/collection/L22/current/TOOL1810/

TOOL1810 - Onset HOBO U26-001 Dissolved Oxygen Data Logger
