### ISSUE TITLE
NTR: RBRquartz³ BPR|zero (BODCNVS-1695)

### ISSUE THREAD

**Issue by nadiakreimer** [nvs-vocabs/L22#131]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
RBR

## Device range
N/A

## Device model
quartz³ BPR zero

## Model version
N/A

## Model alternative name (if applicable)
N/A

## Modification (if applicable)
N/A

## Qualification (if applicable)
Zero

## Instrument type
Bottom Pressure Recorder

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
N/A

## Short name
RBRquartz³ BPR|zero

## Documentation
https://rbr-global.com/products/standard-loggers/rbrquartz-bpr-zero

## Mapping to external terminologies (optional)
N/A

## ORCID (optional)
0000-0002-8162-2383

**Comment by SLBlakeman** [comment]
The new term has been created and is now available on the NVS:
TOOL1909 - RBR Quartz 3 BPR Zero bottom pressure recorder
