### ISSUE TITLE
NTR: Far Red Mounted LED, M730L4, Thorlabs Inc (BODCNVS-1696)

### ISSUE THREAD

**Issue by adyork** [nvs-vocabs/L22#133]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Thorlabs Inc

## Device range
Far Red (730 nm) Mounted LED, 1000 mA, 515 mW

## Device model
M730L4

## Model version
n/a

## Qualification (if applicable)
mounted

## Instrument type
LED

## Does the tool describe a series of instruments? 
individual

## Short name
Far Red (730 nm) Mounted LED, 1000 mA, 515 mW

## Documentation
https://www.gophotonics.com/products/led-light-emitting-diodes/thorlabs-inc/25-46-m730l4

The M730L4 from Thorlabs Inc is a LED with Current 1000 mA, Forward Voltage 2.3 V, Wavelength 730 nm, Power 515 to 595 mW. More details for M730L4 can be seen below.

**Comment by JordanAthertonNOC** [comment]
Dear @adyork 

Thanks for your interest in the L22 vocabulary and apologies for the delay in addressing this - it was regrettably missed from our internal tracking procedure. As this LED does not in itself collect, sample or measure anything it does not fall within the remit of the L22 collection "_Terms for distinct sampling or measuring devices that may be identified in the real world in terms of manufacturer and model number._". If the LED has been used specifically in conjunction with a sensor and its inclusion is notable, we can explore including this in the term description for the sensor - feel free to reopen the ticket if that's the case. 

Best

Jordan
