### ISSUE TITLE
NTR: ICES built MIK net [BODCNVS-1459]

### ISSUE THREAD

**Issue by JoBeja** [nvs-vocabs/L22#135]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
ICES

## Device range
n/a

## Device model
Midwater Ringnet

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
The MIK net consists of a rigid ring frame to which the net is attached, a conical net made of nylon gauze, a codend bucket, a pair of bridles for towing, a depressor with bridles, a flowmeter for filtered volume determination and a depth gauge for monitoring net depth:
a ) Ring of 2 metre diameter. This should be reasonably strong, preferably made of two connected steel tubes (picture in Annex 1). When the ring is heavy (~100kg) there is no need for a depressor, but only a weight to stabilize the ring (see “d” below).
b ) Black net of 1.6 mm pore, 13 metre long, strengthened by nylon or canvas straps. In the last metre of the net a 500 μm net is inserted (Figure b1 in Annex 1).
c ) Straps (with nuts, bolts and plates) or a strong line for mounting the net on the ring.
d ) Saddle shaped weight or depressor of approximately 25kg or more where necessary dependent on weight of the 2m ring.
e ) Pair of 10 metre long bridles to the gear. This length in order to keep the bridles away from the path into the net.
f ) Pair of 3.0 metre long bridles to the weight or depressor. This length is needed in order to keep bridles away from touching the net.
g ) Codend bucket (Ø 11 cm) for collection of the plankton sample. Use a netting of 500 μm or less for the codend (see examples).
h ) Flowmeter mounted on a string crossing the ring, positioned in the centre of the ring. Keep string slack so that flowmeter is approximately 0.5 m inside the net. Suggested flowmeter types are General Oceanic 2030R or the newer types of Hydrobios 438 110.
i ) In order to monitor the depth of the gear (and thereby calculate the distance to bottom) a depth sounder with acoustic transmission should be mounted in the ring.

## Qualification (if applicable)
n/a

## Instrument type
Fish Larvae sampling net

## Does the tool describe a series of instruments? 
individual instrument

## Reference (if applicable)
ICES. 2013. Manual for the Midwater Ring Net sampling during IBTS Q1. Series of ICES Survey Protocols SISP 2-MIK 2. 18 pp.

## Short name
MIK net

## Documentation
Documentation mentioned above will be sent over email to the vocab team

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
 https://orcid.org/0000-0002-5196-8447

**Comment by danibodc** [comment]
This term has now been created:

NETT0201	ICES MIK Midwater Ringnet

It will be live on the NVS from 0730 UTC tomorrow morning.

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/L22/current/NETT0201/
