### ISSUE TITLE
NTR: Kongsberg SBP-29

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#140]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Kongsberg

## Device range
n/a

## Device model
Sub-bottom profiler (SBP)

## Model version
29

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
Sub-bottom profiler

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
SBP-29

## Documentation
https://www.kongsberg.com/maritime/products/ocean-science/mapping-systems/sub-bottom-profilers2/sub-bottom-profiler-sbp29/

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
This term has now been created: Kongsberg SBP 29 Sub-bottom profiler (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1825/)

Let us know if there are any issues.
