### ISSUE TITLE
NTR: ixBlue Phins Surface

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#141]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
ixBlue

## Device range
n/a

## Device model
Phins Surface

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
Inertial Navigation System (INS)

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
Phins Surface

## Documentation
https://www.ixblue.com/north-america/store/phins-surface/

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
This term has now been created: iXblue Phins Surface Inertial Navigation System (INS) (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1823/)

Let us know if there are any issues.
