### ISSUE TITLE
NTR: SBE 50

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#143]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Seabird

## Device range
SBE

## Device model
n/a

## Model version
50

## Model alternative name (if applicable)
na

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
Pressure sensor

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
SBE 50

## Documentation
https://www.seabird.com/moving-platform/sbe-50-digital-oceanographic-pressure-sensor/family-downloads?productCategoryId=54627473794&_bk=&_bm=&_bt=454319501975&_bn=g&_bg=106447525872&_bt=454319501975&_bk=&_bm=&_bn=g&utm_id=go_cmp-10754372780_adg-106447525872_ad-454319501975_dsa-527914770380_dev-c_ext-_prd-_sig-CjwKCAjw_b6WBhAQEiwAp4HyICImOWa-vODwWG18C6DVeXfQaG6MDiLfy7UBpdw-UDs8eYJyxCA_fBoCu-oQAvD_BwE&utm_source=google&gclid=CjwKCAjw_b6WBhAQEiwAp4HyICImOWa-vODwWG18C6DVeXfQaG6MDiLfy7UBpdw-UDs8eYJyxCA_fBoCu-oQAvD_BwE

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
This term has now been created: SBE 50 pressure sensor (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1824/)

Let us know if there are any issues
