### ISSUE TITLE
NTR: Observator OMC-116M Ultrasonic Wind Sensor

### ISSUE THREAD

**Issue by alex-tate** [nvs-vocabs/L22#146]
## Device make
Observator

## Device range
N/A

## Device model
OMC-116

## Model version
M (marine version, varies only in the mounting option from the land version [OMC-116]) 

## Model alternative name (if applicable)
N/A

## Modification (if applicable)
N/A

## Qualification (if applicable)
Full Metal

## Instrument type
Anemometer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
N/A

## Short name
observator_omc116m

## Documentation
https://observator.com/products/omc-116-full-metal-ultrasonic-wind-sensor/

## Mapping to external terminologies (optional)
N/A

## ORCID (optional)
0000-0002-7880-3271

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from 07:30 UTC tomorrow morning:

TOOL1833 - Observator OMC-116M ultrasonic wind sensor

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1833/
