### ISSUE TITLE
NTR: Biral SWS-100 Visibility Sensor

### ISSUE THREAD

**Issue by alex-tate** [nvs-vocabs/L22#149]
## Device make
Biral

## Device range
N/A

## Device model
SWS-100

## Model version
N/A

## Model alternative name (if applicable)
N/A

## Modification (if applicable)
N/A

## Qualification (if applicable)
N/A

## Instrument type
Visibility sensor (from L05, 'atmospheric transparency quantifiers', possibly also 'precipitation gauges' and 'meteorological packages')

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
N/A

## Short name
biral_sws100

## Documentation
https://www.biral.com/product/sws-100-visibility-sensor/#product-overview

## Mapping to external terminologies (optional)
N/A

## ORCID (optional)
0000-0002-7880-3271

**Comment by danibodc** [comment]
This term has been loaded and will be live on the NVS from 07:30 UTC tomorrow morning:

TOOL1832 - Biral SWS-100 visibility sensor

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1832/
