### ISSUE TITLE
NTR: Magee Scientific AE33 Aethalometer

### ISSUE THREAD

**Issue by alex-tate** [nvs-vocabs/L22#151]
## Device make
Magee Scientific

## Device range
N/A

## Device model
AE33

## Model version
7 (the front of the device gives its name as an AE33-7 but this isn't listed as a model version in any of the documentation. Possibly refers to the fact that the black carbon analysis is performed at seven optical wavelengths so can be ignored) 

## Model alternative name (if applicable)
N/A

## Modification (if applicable)
N/A

## Qualification (if applicable)
N/A

## Instrument type
Aethalometer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
N/A

## Short name
magee_ae33

## Documentation
https://mageesci.com/mproducts/magee-scientific-aethalometer/

## Mapping to external terminologies (optional)
N/A

## ORCID (optional)
0000-0002-7880-3271

**Comment by roswri** [comment]
Hi @alex-tate,

Your new term has now been created:
Magee Scientific AE33 Aethalometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1852/)

It is queued for publication on the NVS and should be live tomorrow morning.

Best wishes,
Roseanna
