### ISSUE TITLE
NTR: Skipper Electronics GDS102 Echosounder

### ISSUE THREAD

**Issue by alex-tate** [nvs-vocabs/L22#154]
## Device make
Skipper Electronics

## Device range
n/a

## Device model
GDS102

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
single-beam echosounder

## Does the tool describe a series of instruments? 
It has several transducers so possibly a system of instruments.

## Reference (if applicable)
n/a

## Short name
skipper_gds102

## Documentation
https://www.skipper-service.no/skipdoc/data////Manuals//Navigational%20Echo%20Sounders/GDS102%20Echosounder/GDS102%20Operation%20and%20Installation%20Manual%202019-08-28.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-7880-3271

**Comment by SLBlakeman** [comment]
Hi @alex-tate,

Thank you for submitting your request for a new L22 term. It has now been created:

TOOL1835 - Skipper Electronics GDS102 single-beam echosounder

and can be found on the NVS:

http://vocab.nerc.ac.uk/collection/L22/current/TOOL1835/ .
