### ISSUE TITLE
NTR: Bulk Request for Multiple Video Camera Makes and Models (BODCNVS-1496)

### ISSUE THREAD

**Issue by ssmosstee** [nvs-vocabs/L22#157]
Hi there,
We at Ocean Networks Canada are requesting several cameras be added to the L22 vocabulary. These cameras have all been used in the field for our underwater observatory system and since we use BODC as our controlled vocabulary bank, we will need these makes and models added. I'll place the makes that are covered in the body of this message, but plesae refer to the bulk request template for other information.

## Device make

Axis Communications
Canon
DeepSea   Power & Light
GoPro
Hanwha Techwin
Imenco
Insite  Pacific Inc
Kongsberg Maritime
Nikon
Ocean Presence Technologies
Olympus
Panasonic 
ROS
Sidus Solutions LLC
Sony
StarDot Technologies
SubC Imaging

## Bulk Template File
See here:
[L22_batch_5_submissions_cameras.xlsx](https://github.com/nvs-vocabs/L22/files/9193742/L22_batch_5_submissions_cameras.xlsx)

Thanks for your time,
Sean Tippett

**Comment by JordanAthertonNOC** [comment]
47 new terms created and loaded to the NVS.
