### ISSUE TITLE
NTR: Metrohm 805 Dosimat

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/L22#176]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Metrohm

## Device range
Dosimat

## Device model
805

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
Dosimat

## Instrument type
dosing drive

## Reference (if applicable)
https://www.metrohm.com/en_au/products/2/8050/28050010.html

## Short name
Metrohm 805

## Documentation
https://www.metrohm.com/en_au/products/2/8050/28050010.html

## Mapping to external terminologies (optional)
https://vocab.nerc.ac.uk/collection/B75/current/ORG00620/

## ORCID (optional)
0000-0002-9081-1004

**Comment by SLBlakeman** [comment]
Hello @whshannon,

The new term: TOOL1893 - Metrohm 805 Dosimat Burette has been created and is now available on the NVS.
