### ISSUE TITLE
NTR: Turner C3 Submersible Fluorometer (BODCNVS-1647)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#177]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Turner

## Device range
n/a

## Device model
C3

## Model version
n/a

## Model alternative name (if applicable)
Turner C3

## Modification (if applicable)
n/a

## Qualification (if applicable)
submersible

## Instrument type
fluorometer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
Turner C3

## Documentation
https://www.turnerdesigns.com/c3-submersible-fluorometer

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
0000-0002-0017-8330

**Comment by SLBlakeman** [comment]
Hello,

The new L22 term is now available on the NVS:

TOOL1907 - Turner Designs C3 submersible fluorometer

https://vocab.nerc.ac.uk/collection/L22/current/TOOL1907/
