### ISSUE TITLE
NTR: Knudsen KEL771 28/200kHz (BODCNVS-1648)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#178]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Knudsen

## Device range
KEL

## Device model
771

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
dual frequency transducer

## Instrument type
Transducer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
KEL771

## Documentation
https://knudseneng.com/files/brochures/transducers/dual-freq/kel-771.pdf

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
New term loaded, and now live on the NVS:
Knudsen KEL 771 dual frequency transducer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1915/)
