### ISSUE TITLE
NTR: Picarro G2301 (BODCNVS-1699)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#184]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Picarro

## Device range
n/a

## Device model
G2301

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
gas analyzer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
G2301

## Documentation
(https://www.picarro.com/g2301_gas_concentration_analyzer#:~:text=The%20Picarro%20G2301%20gas%20concentration,air%20quality%2C%20and%20emissions%20quantification.)

## Mapping to external terminologies (optional)
L05/382

## ORCID (optional)
0000-0002-0017-8330

**Comment by danibodc** [comment]
This term has now been loaded to L22 and will be live on the NVS from tomorrow morning;

TOOL1918	Picarro G2301 gas analyser

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1918/
