### ISSUE TITLE
NTR: X-band radar (BODCNVS-1713)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#187]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Helmholtz-Zentrum Hereon

## Device range
n/a

## Device model
X-band radar

## Model version
n/a

## Model alternative name (if applicable)
Hereon Radar

## Modification (if applicable)
n/a

## Qualification (if applicable)
 coherent-on-receive marine X-band radar

## Instrument type
Radar

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
Hereon Radar

## Documentation
https://miamiedu-my.sharepoint.com/personal/blund_miami_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fblund%5Fmiami%5Fedu%2FDocuments%2FAttachments%2Fsensors%2D21%2D07828%2Dv3%201%2Epdf&parent=%2Fpersonal%2Fblund%5Fmiami%5Fedu%2FDocuments%2FAttachments&ga=1

https://www.hereon.de/institutes/carbon_cycles/cosyna/observations/radar/index.php.en

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by danibodc** [comment]
Hi @rhudak2020, I am not able to access the Sharepoint link above. Are you able to email the document to vocab.services@bodc.ac.uk?

Many thanks!

**Comment by rhudak2020** [comment]
Hi Dani,
Apologies for the link, I can attach it here as well as email vocab.services@bodc.ac.uk

Cheers!
[sensors-21-07828-v3 1.pdf](https://github.com/nvs-vocabs/L22/files/11578083/sensors-21-07828-v3.1.pdf)

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1958/
