### ISSUE TITLE
NTR: Guralp Orcus Ocean Bottom Seismometer (BODCNVS-1715)

### ISSUE THREAD

**Issue by nadiakreimer** [nvs-vocabs/L22#188]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Guralp

## Device range
N/A

## Device model
Orcus Ocean Bottom Seismometer System

## Model version
N/A

## Model alternative name (if applicable)
N/A

## Modification (if applicable)
As per Instrument Manual:
* The 3T broadband seismometer sensor within the Orcus can have its frequency range and sensitivity engineered to fit the requirement of the project.
* The 5T strong-motion accelerometer within the Orcus can have its frequency range and gain engineered to fit the requirement of the project. 
* Depending on the deployment depth, the unique spherical casing is composed of either duplex stainless steel or titanium to protect the instrument against water pressure and corrosion. 
* The Orcus may be integrated with a number of additional geophysical sensors including: a differential pressure gauge (DPG), absolute pressure gauge (APG), current meter, hydrophone, compass and tilt-meter

## Qualification (if applicable)
Ocean Bottom

## Instrument type
Seismometer

## Does the tool describe a series of instruments? 
System

## Reference (if applicable)
N/A

## Short name
Orcus seismometer

## Documentation
* Manufacturer website: [https://www.guralp.com/products/ocean-bottom-seismometers]
* Datasheet: [https://www.guralp.com/documents/DAS-ORC-0001.pdf]
* Technical manual: [https://www.guralp.com/documents/html/MAN-OBS-0013/]
* As per Instrument Manual (not available online, but I can provide it, if desired):
** The Güralp Orcus OBS contains two seismometers: a 5T strong motion triaxial accelerometer, and a 3T weak motion triaxial seismometer. 
** For details of the Güralp 3T sensor you are referred to the specific manual, which can be downloaded from: https://www.guralp.com/documents/MAN-030-0001. 
** For details of the Güralp 5T sensor, you are referred to the specific manual, which can be downloaded from: https://www.guralp.com/documents/MAN-050-0001.
** The Affinity manual represents a detailed Users' Guide for the digitiser, which can be downloaded from: http://www.guralp.com/documents/MAN-AFT-0001.  This manual provides details of the features which are unique to the Affinity, including configuration and operation of the built-in ADCs and the connector pin-out. The Güralp Affinity runs the Platinum operating system, which is common to many Güralp data acquisition modules, including the EAM, the NAM and the legacy DCM. Platinum provides rich web and command-line interfaces to configure, control and monitor all data storage, protocol conversion, and communications functions. These features of the Affinity are all described in the Platinum manual, MAN-EAM-0003, which is available to download at the following link http://www.guralp.com/documents/MAN-EAM-0003.

## Mapping to external terminologies (optional)
N/A

## ORCID (optional)
0000-0002-8162-2383

**Comment by JordanAthertonNOC** [comment]
Hi @nadiakreimer 

One new L22 term has been created for this request and will go live on the NVS tomorrow after ~07:30 BST.

Guralp Orcus ocean bottom seismometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1925/)

Best

Jordan
