### ISSUE TITLE
NTR: SonTek CastAway-CTD (BODCNVS-1757)

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/L22#189]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
SonTek/Xylem

## Device range
SonTek CastAway-CTD

## Device model
SonTek CastAway-CTD

## Model version
n/a 

## Model alternative name (if applicable)
n/a 

## Modification (if applicable)
n/a 

## Qualification (if applicable)
handheld castable CTD

## Instrument type
CTD

## Does the tool describe a series of instruments? 
an individual instrument that measures multiple parameters 

## Reference (if applicable)
n/a

## Short name
CastAway-CTD

## Documentation
website: https://www.xylem.com/en-us/brands/wtw/wtw-products/castaway-ctd/
spec sheet from website: https://www.xylem.com/siteassets/brand/sontek/resources/specification/sontek-castaway-ctd-spec-sheet-2018.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-9081-1004

**Comment by JordanAthertonNOC** [comment]
Hi @whshannon 

One new L22 has been created and should be live on the NVS from ~04:00 EDT tomorrow.

SonTek CastAway CTD (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1926/)

Best

Jordan
