### ISSUE TITLE
NTR: McLane Large Volume Pumping System WTS-LV (BODCNVS-1764)

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/L22#190]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
McLane Labs

## Device range
Large Volume Water Transfer System (WTS-LV)

## Device model
Large Volume Water Transfer System (WTS-LV)

## Model version
n/a; multiple

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
The WTS-LV is available in four different configurations: Standard, Upright, Bore Hole, and Dual Filter Sampler.  A high capacity upright WTS-LV model provides three times the battery life of the standard model. The Bore-Hole WTS-LV is designed to fit through a narrow opening such as a 30cm bore-hole. The WTS-LVDF features two vertical intake 142 mm filter holders to allow simultaneous filtering using two different porosities.

## Qualification (if applicable)
n/a

## Instrument type
water pump; large volume single-event sampler 

## Does the tool describe a series of instruments? 
Yes. See above; there are 4 configurations available. Perhaps each warrants its own L22 term? 

## Reference (if applicable)
https://mclanelabs.com/wts-lv-large-volume-pump/

## Short name
WTS-LV

## Documentation
https://mclanelabs.com/wts-lv-large-volume-pump/

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
0000-0002-9081-1004

**Comment by JordanAthertonNOC** [comment]
Hi @whshannon, one new L22 has been created and should go live on the NVS at ~02:00 EST tomorrow. 

McLane Large Volume Water Transfer System (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1960/)

**Comment by whshannon** [comment]
Thanks!
