### ISSUE TITLE
NTR: Turo Quoll XBT System (BODCNVS-1890)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#194]
## Device make
Turo

## Device range
n/a

## Device model
Quoll 

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
XBT system

## Does the tool describe a series of instruments? 
n/a

## Reference (if applicable)
n/a

## Short name
Turo Quoll

## Documentation
https://www.turo.com.au/index.php/products/quoll-xbt

## ORCID (optional)
0000-0002-0017-8330

**Comment by JordanAthertonNOC** [comment]
Hi Rebecca

Just to clarify - for this request are you looking for a term covering the system including the recorder (from the link provided) along with an XBT probe (description specific to Sippican XBT probes?), or just the recorder?

**Comment by rhudak2020** [comment]
@JordanAthertonNOC I think just the recorder/system is sufficient

**Comment by JordanAthertonNOC** [comment]
One new L22 has been created and will be live on the NVS from around ~06:00 UTC tomorrow. 

Turo Quoll XBT recorder (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1988/)
