### ISSUE TITLE
NTR: RM Young 92000 [BODCNVS-1927]

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#198]
## Device make
RM Young

## Device range
n/a

## Device model
92000 ResponseONE

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
Weather Transmitter

## Does the tool describe a series of instruments? 
n/a

## Reference (if applicable)
n/a

## Short name
RM Young 92000

## Documentation
https://www.youngusa.com/wp-content/uploads/2016/12/92000-90H.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by JordanAthertonNOC** [comment]
This term has now been created and is queued for publication on the NVS:
RM Young 92000 ResponseONE weather transmitter (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2010/)
