### ISSUE TITLE
NTR: JRC JLR-21 GPS Compass [BODCNVS-1928]

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#199]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Japan Radio Company 

## Device range
JLR

## Device model
JLR-21

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
gps compass

## Does the tool describe a series of instruments? 
no

## Reference (if applicable)
n/a

## Short name
JLR-21

## Documentation
https://www.jrc.co.jp/en/product/jlr21_31

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by JordanAthertonNOC** [comment]
This term has now been created and is queued for publication on the NVS:
Japan Radio Co (JRC) JLR-21 GPS compass (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2011/)
