### ISSUE TITLE
NTR: Rotor Flow RFO/RFA-2500 [BODCNVS-1929]

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#200]
## Device make
Gems Sensors and Controls

## Device range
Rotor Flow

## Device model
RFO/RFA-2500

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
flow meter

## Does the tool describe a series of instruments? 
series

## Reference (if applicable)
n/a

## Short name
RFO/RFA-2500

## Documentation
https://www.instrumart.com/assets/Gems-RFA-installation.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
Hi @rhudak2020,

This term has now been created and s live on the NVS:
Gems Sensors and Controls RotorFlow RFO/RFA-2500 (Continuous Output) flow meter Series (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2071/)
