### ISSUE TITLE
NTR: Turo Devil XBT Recorder (BODCNVS-1958)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#203]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Turo

## Device range
n/a

## Device model
Devil

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
XBT recorder

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
Turo Devil

## Documentation
https://www.turo.com.au/index.php/products/devil-xbt

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by vpaba** [comment]
Hi @rhudak2020,

Thanks for your patience. A new L22 entry has now been created:

- TOOL2014 - Turo Devil XBT recorder

Please let us know if you find any issues.

Kind regards,
Violetta
