### ISSUE TITLE
NTR: E+E Elektronik EE060 Humidity and Temperature Probe (BODCNVS-1957)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#204]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
E+E Elektronik

## Device range
EE06x

## Device model
EE060

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
weather station

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
EE060

## Documentation
https://www.epluse.com/products/humidity-instruments/humidity-modules-and-probes/ee060-ee061/

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by vpaba** [comment]
Hi @rhudak2020, 

Thanks for your patience. A new L22 entry has now been created:

- TOOL2015 - E+E Elektronik EE060 humidity and temperature probe

Please let us know if you find any issues.

Kind regards,
Violetta
