### ISSUE TITLE
NTR: E+E Elektronik EE08 Humidity and Temperature Probe (BODCNVS-1956)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#205]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
E+E Elektronik

## Device range
n/a

## Device model
EE08

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
weather station

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
EE08

## Documentation
https://www.epluse.com/products/humidity-instruments/humidity-modules-and-probes/ee08/

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
Hi @rhudak2020,

New term created and queued for publication on the NVS: E+E Elektronik EE08 humidity and temperature probe (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2016/). The link should go live early tomorrow morning.
