### ISSUE TITLE
NTR: Seametrics SES-050-13 (BODCNVS-1953)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#208]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Seametrics

## Device range
n/a

## Device model
SES

## Model version
050-13

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
flow meter

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
SES-050-13

## Documentation
https://www.seametrics.com/wp-content/uploads/LT-65650124r2.2-20220524-SES-Specs-1.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
Hi @rhudak2020,

This terms has now ben created and is live on the NVS: 
Seametrics SES 050-13 flow meter (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2070/)
