### ISSUE TITLE
NTR: Seapath 380-R series [BODCNVS-1968]

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#212]
## Device make
Kongsberg

## Device range
Seapath

## Device model
380

## Model version
R

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
gnss/imu

## Does the tool describe a series of instruments? 
R series (R2, R3, R4)

## Reference (if applicable)
n/a

## Short name
Seapath 380-R

## Documentation
https://www.kongsberg.com/contentassets/c22a596095db4994a5f26ba216b6b968/110-0017979a_datasheet_seapath380-r_dec22.pdf

## Mapping to external terminologies (optional)
L22:TOOL1623

## ORCID (optional)
0000-0002-0017-8330

**Comment by jakjonbodc** [comment]
TOOL2025 - Kongsberg Seatex Seapath 380-R Heading, Attitude and Positioning sensor series

https://vocab.nerc.ac.uk/collection/L22/current/TOOL2025/
