### ISSUE TITLE
NTR: SMBA box corer [BODCNVS-1970]

### ISSUE THREAD

**Issue by jamcas-bas** [nvs-vocabs/L22#213]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Scottish Marine Biological Association

## Device range
n/a

## Device model
n/a

## Model version
n/a

## Instrument type
box corer

## Does the tool describe a series of instruments? 
individual

## Short name
SMBA box corer

## Documentation
https://noc.ac.uk/facilities/national-marine-equipment-pool/scientific-engineering/seafloor-sampling
(entry: SMBA box corer)

**Comment by roswri** [comment]
New term created and live on the NVS: 
Scottish Marine Biological Association box corer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2029/)
