### ISSUE TITLE
NTR: NIOZ trigger corer [BODCNVS-2010]

### ISSUE THREAD

**Issue by jamcas-bas** [nvs-vocabs/L22#216]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Inapplicable

## Device range
n/a

## Device model
n/a

## Model version
n/a

## Model alternative name (if applicable)
NIOZ trigger corer

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
trigger corer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
NIOZ trigger corer

## Documentation
**Instrument type description:** A trigger corer.

**Operating principle:** The corer consists of a core bomb fitted with a 0.75 m length steel core barrel lined with a 63 mm diameter PVC liner. The trigger corer is a gravity corer type: the corer is lowered on a wire to the seabed, and the core barrel penetrates the sediment by its own weight. The contact of the trigger corer with the sediment is the trigger for the release of the associated piston corer into freefall. Built for the British Antarctic Survey in 2014 by P. Smit BV, NIOZ (Koninklijk Nederlands Instituut voor Onderzoek der Zee, the Royal Netherlands Institute for Sea Research). 

**Description source:** Rob Larter, BAS, _pers comm_

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by jamcas-bas** [comment]
Instrument type: should be 'trigger corer'

**Comment by danibodc** [comment]
This has been loaded to L22 and will be live on the NVS from tomorrow morning:

TOOL2047	NIOZ custom trigger corer system

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/L22/current/TOOL2047/
