### ISSUE TITLE
NTR: Calvert box corer [BODCNVS-2008]

### ISSUE THREAD

**Issue by jamcas-bas** [nvs-vocabs/L22#218]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Inapplicable

## Device range
n/a

## Device model
n/a

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
box corer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
Calvert et al, 1980

## Short name
Calvert box corer

## Documentation
https://nora.nerc.ac.uk/id/eprint/114392/1/14392-01.pdf
https://www.ofeg.org/np4/37/%7B$clientServletPath%7D/?newsId=66&fileName=OFEG_corers___Jez_Evans___NOC.pdf (p3, Calvert Box Corer)

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by roswri** [comment]
New term created and live on NVS:
Institute of Oceanographic Sciences box corer - Calvert et al (1980) (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2028/)
