### ISSUE TITLE
NTR: LI-7815 CO2/H2O Trace Gas Analyzer [BODCNVS-2016]

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/L22#219]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
LI-COR Biosciences

## Device range
LI-7815

## Device model
n/a

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
CO2/H2O Trace Gas Analyzer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
[https://www.licor.com/env/support/LI-7815/topics/introduction.html#:~:text=The%20LI%2D7815%20CO2,is%20described%20in%20published%20literature.](https://www.licor.com/env/support/LI-7815/topics/introduction.html#:~:text=The%20LI%2D7815%20CO2,is%20described%20in%20published%20literature.)

## Short name
LI-7815 Trace Gas Analyzer

## Description
The LI-7815 CO2/H2O Trace Gas Analyzer is a high-precision, high-stability, laser-based gas analyzer that uses Optical Feedback - Cavity-Enhanced Absorption Spectroscopy (OF-CEAS) to measure gases in air. OF-CEAS is a well-established spectroscopic technique that is described in published literature. The analyzer reports and stores in its internal memory CO2 dry mole fractions in air corrected for both the spectroscopic interferences and dilution due to H2O.

**Comment by JordanAthertonNOC** [comment]
One new term created, live on the NVS after ~07:00 GMT tomorrow. 

LI-COR LI-7815 CO2/H2O trace gas analyser (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2021/)
