### ISSUE TITLE
NTR: AML Plus X

### ISSUE THREAD

**Issue by mcuthill** [nvs-vocabs/L22#22]
Note: this is a term that was requested in the past but never quite came to fruition, probably due to the modular nature of the device. While functionally the Plus X is usually deployed as a CTD + secondary/aux sensors, technically the base Plus X has no hard-mounted sensors and therefore could become several different device types. Therefore I'm suggesting the instrument type be classified as 'data logger' and the particular sensor array captured elsewhere in user metadata. I welcome any expert insight into the matter.

## Device make
AML Oceanographic

## Device model
Plus X

## Model version
P1S2 (Not sure if this level of granularity is needed. There are multiple versions of the instrument, named for the number of Primary (P) and Auxiliary (S) sensor ports. Our instruments are all P1S2 according to the invoices, though the manual only lists P1S3 and P2S2.)

## Instrument type
Data Logger

## Does the tool describe a series of instruments? 
Is part of the AML Oceanographic X Series of instruments which work with swappable XChange sensors; full series can be seen at https://amloceanographic.com/all-instrumentation/ 

## Short name
AML PLUS X

## Documentation
https://amloceanographic.com/product/plus-x/ - manual available under Downloads

**Comment by louatbodc** [comment]
Thank you for your patience. Agreed - this seems more like a data logger which are now acceptable in L22. We have created a new term for you:

AML Oceanographic X Series Plus X data logger (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1410/)

Please note, it may take up to 24 hrs for the new term to appear on our web services.

**Comment by louatbodc** [comment]
Thank you for your patience. Agreed - this seems more like a data logger which are now acceptable in L22. We have created a new term for you:

AML Oceanographic X Series Plus X data logger (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1410/)

Please note, it may take up to 24 hrs for the new term to appear on our web services.
