### ISSUE TITLE
NTR: Chromium Controller [BODCNVS-2029]

### ISSUE THREAD

**Issue by adyork** [nvs-vocabs/L22#228]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
[This is the name of the manufacturer or institution which made the instrument. If there is a manufacturer but you have not been able to confirm this information or there is no official manufacturer, input 'Inapplicable'. If you are creating a generic instrument (e.g. a generic temperature sensor, then input 'Unspecified'.]

10x Genomics

## Device range
[The manufacturer's instrument model range (e.g. WindObserver). If there is no official model range then input 'n/a'.]

## Device model
[Name of the instrument model. If there is no official model name, input 'n/a'.]

Chromium Controller

## Model version
[Name of the sub-model (e.g. 'D', 'v3.2'). If there is no official version/sub-model then input 'n/a'.]
n/a

## Model alternative name (if applicable)
[Alternative name for the model. E.g. Glider Payload CTD alternative name is GPCTD]

## Modification (if applicable)
[Describes any modifications to the instrument design, such as a manufactured device that has been modified 'in-house' or a plakton net that has been modified since its first description.]

## Qualification (if applicable)
[Qualification of the instrument type i.e. a word or words that further describe the instrument type (e.g. 'portable','automated','pressure-compensated','large' etc.). Sometimes these are used in manufacturer names.]

## Instrument type
[Please indicate what type of instrument it is (e.g. global positioning system, fluorometer, etc.)]

single cell partitioning and barcoding
Single Cell Gene Expression
Single cell RNA sequencing

(from https://www.10xgenomics.com/instruments/chromium-controller)

The Chromium Controller uses advanced microfluidics to perform single cell partitioning and barcoding in a matter of minutes. Powered by Next GEM technology, the Chromium Controller enables integrated analysis of single cells at massive scale.
(https://www.10xgenomics.com/instruments/chromium-controller)

## Does the tool describe a series of instruments? 
[Does the term describe a manufacturing 'series' of instruments, a 'system' of instruments, an 'individual' instrument or other?]

no

## Reference (if applicable)
[Citation for the instrument (e.g. Hall and Bumpus 1937, 1944). Use if the instrument is manufactuered and built according to a design in a paper.]

## Short name
[Shortened name of the instrument. This is usually a shortened version of name limited to make, model and version. It can also be an alternative name.]

## Documentation
[Please enter a link to the documentation describing the instrument. This could be a journal reference, manufacturer data sheet, web site, manual etc.]

https://www.10xgenomics.com/instruments/chromium-controller
https://www.10xgenomics.com/platforms/chromium#instrument

Specifications: https://support.10xgenomics.com/genome-exome/index/doc/specifications-chromium-controller-specifications

Resources:
https://www.10xgenomics.com/support/instruments/chromium-controller?query=&page=1&configure%5Bfilters%5D=instruments.slug%3Achromium-controller

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by JordanAthertonNOC** [comment]
Hi @adyork 

Thank you for your request. This term has now been created and will go live on the NVS at ~03:00 ET tomorrow, the link will not resolve until then but the identifier will remain unchanged. 

10x Genomics chromium controller single cell analyser (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2022/)
