### ISSUE TITLE
NTR: Bell Aerospace TEXTRON; BGM-3 [BODCNVS-2051]

### ISSUE THREAD

**Issue by snehalprabhu10** [nvs-vocabs/L22#231]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Bell Aerospace / TEXTRON

## Device range
BGM

## Device model
3

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
Gravimeter

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
BGM-3

## Documentation
https://www2.whoi.edu/site/miso/miso-instrumentation/623-2/

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by jakjonbodc** [comment]
New L22 term is available on NVS:
https://vocab.nerc.ac.uk/collection/L22/current/TOOL2063/
Bell Aerospace BGM 3 marine gravimeter
