### ISSUE TITLE
NTR: Kongsberg EM2040 MKII [BODCNVS-2076]

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#232]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Kongsberg

## Device range
EM

## Device model
EM2040 MKII

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
echosounder

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
EM2040 MKII

## Documentation
https://www.kongsberg.com/globalassets/maritime/km-products/product-documents/em-2040-mkii-data-sheet2.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
New term created: Kongsberg EM 2040 MKII multibeam echosounder (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2039/)
Should go live on NVS early tomorrow
