### ISSUE TITLE
NTR: Thermo Scientific NanoDrop spectrophotometer [BODCNVS-2151]

### ISSUE THREAD

**Issue by lmerchant** [nvs-vocabs/L22#234]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make

Thermo Fisher Scientific™ (https://www.thermofisher.com/us/en/home.html)

## Device range
[The manufacturer's instrument model range (e.g. WindObserver). If there is no official model range then input 'n/a'.]

NanoDrop

## Device model
[Name of the instrument model. If there is no official model name, input 'n/a'.]

n/a

## Model version
[Name of the sub-model (e.g. 'D', 'v3.2'). If there is no official version/sub-model then input 'n/a'.]

n/a

## Model alternative name (if applicable)
[Alternative name for the model. E.g. Glider Payload CTD alternative name is GPCTD]

n/a

## Modification (if applicable)
[Describes any modifications to the instrument design, such as a manufactured device that has been modified 'in-house' or a plakton net that has been modified since its first description.]

n/a

## Qualification (if applicable)
[Qualification of the instrument type i.e. a word or words that further describe the instrument type (e.g. 'portable','automated','pressure-compensated','large' etc.). Sometimes these are used in manufacturer names.]

A Thermo Scientific NanoDrop spectrophotometer provides microvolume quantification and purity assessments of DNA, RNA, and protein samples. The results appear in seconds. NanoDrop spectrophotometers work on the principle of ultraviolet-visible spectrum (UV-Vis) absorbance.

## Instrument type
[Please indicate what type of instrument it is (e.g. global positioning system, fluorometer, etc.)]

spectrophotometer

## Does the tool describe a series of instruments? 
[Does the term describe a manufacturing 'series' of instruments, a 'system' of instruments, an 'individual' instrument or other?]

It describes a manufacturing series of instruments

## Reference (if applicable)
[Citation for the instrument (e.g. Hall and Bumpus 1937, 1944). Use if the instrument is manufactuered and built according to a design in a paper.]

n/a

## Short name
[Shortened name of the instrument. This is usually a shortened version of name limited to make, model and version. It can also be an alternative name.]

NanoDrop spectrophotometer

## Documentation
[Please enter a link to the documentation describing the instrument. This could be a journal reference, manufacturer data sheet, web site, manual etc.]

https://www.thermofisher.com/us/en/home/industrial/spectroscopy-elemental-isotope-analysis/molecular-spectroscopy/uv-vis-spectrophotometry/instruments/nanodrop.html

https://www.thermofisher.com/us/en/home/industrial/spectroscopy-elemental-isotope-analysis/molecular-spectroscopy/uv-vis-spectrophotometry/instruments/nanodrop/resources.html

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

It is related to the general category of spectrophotometers: 
http://vocab.nerc.ac.uk/collection/L05/current/LAB20/

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by roswri** [comment]
Hello @lmerchant,

This new term has now been created  and should be live on the NVS early tomorrow: Thermo Scientific NanoDrop spectrophotometer Series (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2051/)
