### ISSUE TITLE
NTR: Sunburst AFT-pH [BODCNVS-2172]

### ISSUE THREAD

**Issue by jnahorniak** [nvs-vocabs/L22#240]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Sunburst Sensors

## Device range
n/a

## Device model
AFT-pH

## Model version
n/a

## Model alternative name (if applicable)
Autonomous Flow Through Instrument pH

## Qualification (if applicable)
autonomous

## Instrument type
pH sensors

## Does the tool describe a series of instruments? 
individual

## Short name
Sunburst AFT-pH

## Documentation
http://www.sunburstsensors.com/products/oceanographic-ph-sensor-benchtop.html

## Mapping to external terminologies (optional)
http://vocab.nerc.ac.uk/collection/L05/current/355/
http://vocab.nerc.ac.uk/collection/B75/current/ORG00366/

**Comment by JordanAthertonNOC** [comment]
Hi Jasmine

Thank you for your request, I have now created a new L22 term for this instrument, the link will not resolve until ~23:00 PDT. 
Sunburst Autonomous Flow Through Instrument {AFT-pH} pH sensor (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2068/)
