### ISSUE TITLE
NTR: Tekran Series 2600 Automated Sample Analysis System [BODCNVS-2181]

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/L22#241]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Tekran

## Device range
Automated Sample Analysis System

## Device model
Tekran Series 2600

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
Laboratory sample analysis system

## Does the tool describe a series of instruments? 
No

## Reference (if applicable)
https://www.tekran.com/products/laboratory/tekran-model-2600-automated-total-mercury-analysis-system/

## Short name
Tekran 2600

## Documentation
https://www.tekran.com/products/laboratory/tekran-model-2600-automated-total-mercury-analysis-system/

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-9081-1004

**Comment by roswri** [comment]
New code created: Tekran 2600 (Automated) Total Mercury Analyser series (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2080/)
This should be live on the NVS early tomorrow morning.
