### ISSUE TITLE
NTR: Tekran 2700 Automated Methylmercury Analyzer [BODCNVS-2182]

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/L22#242]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Tekran
## Device range
Tekran 2700

## Device model
Tekran 2700

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
Automated Methylmercury Analyzer

## Instrument type
Laboratory Automated Methylmercury Analyzer

## Does the tool describe a series of instruments? 
n/a

## Reference (if applicable)
https://www.tekran.com/products/laboratory/tekran-model-2700-automated-methyl-mercury-analysis-system/

## Short name
Tekran 2700

## Documentation
https://www.tekran.com/products/laboratory/tekran-model-2700-automated-methyl-mercury-analysis-system/

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-9081-1004

**Comment by roswri** [comment]
New code created: Tekran 2700 (Automated) Methylmercury Analyser (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2079/)
This should be live on the NVS early tomorrow morning.
