### ISSUE TITLE
NTR: Hemisphere GNSS R131 Differential Global Positioning System Receiver [BODCNVS-2186]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#244]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Hemisphere GNSS

## Device range
R100

## Device model
R131

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'rack-mountable','sma-connection','usb-connection'

## Instrument type
Differential global positioning system receiver

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
R131 DGPS Receiver 

## Documentation
https://www.subseatechnologies.com/media/files/page/6b0cf9f8/Hemisphere_GPS_-_R131.pdf

**Comment by jakjonbodc** [comment]
Please find new L22 term:

TOOL2072 - Hemisphere GNSS R131 differential global positioning system receiver

https://vocab.nerc.ac.uk/collection/L22/current/TOOL2072/
