### ISSUE TITLE
NTR: Furuno SC50 Satellite Compass [BODCNVS-2187]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#245]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Furuno

## Device range
SC

## Device model
SC50

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
Satellite Compass

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
SC50

## Documentation
https://www.furunousa.com/en/support/SC50

## Mapping to external terminologies (optional)
n/a

**Comment by JordanAthertonNOC** [comment]
Hi @snionbaven 

This term has now been created and is queued for publication on the NVS tomorrow morning at ~07:00 GMT
Furuno SC-50 GPS receiver and gyrocompass (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2073/)
