### ISSUE TITLE
NTR: HAWBOLDT Industries SPR-2048/RS Winch [BODCNVS-2188]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#246]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
HAWBOLDT Industries

## Device range
n/a

## Device model
SPR-2048/RS

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'UNOLS-compliant','continuous-weld','removeable-drum','planetary-gearbox','multipurpose'

## Instrument type
Trawl winch

## Does the tool describe a series of instruments? 
Individual 

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
n/a

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
n/a

**Comment by jakjonbodc** [comment]
Hello [@snionbaven](https://github.com/snionbaven),
Thank you for submitting a request for a new term. Unfortunately this term does not meet the conditions of our L22 vocabulary, which is designed to contain instruments and sensors that are used to produce data, nor our B76 vocabulary for platforms.
Please do let me know if you have any questions on this matter.
Kind regards,
Jak Jones
