### ISSUE TITLE
NTR: Kipp & Zonen CM21 Pyranometer [BODCNVS-2190]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#248]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Kipp & Zonen 

## Device range
n/a

## Device model
CMP21

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'verified-cosine-response','verified-temperature-dependence','low-dome-IR-offset-error'

## Instrument type
Pyranometer

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://www.kippzonen.com/Product/14/CMP21-Pyranometer#.XpSPE1P7Q6U

## Mapping to external terminologies (optional)
n/a

**Comment by JordanAthertonNOC** [comment]
Hi @snionbaven, this instrument already exists in the L22 collection:
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1502/

**Comment by snehalprabhu10** [comment]
Hi @JordanAthertonNOC 

The original request was for the instrument: Kipp & Zonen CM21 Pyranometer. Would it be possible to create a new vocab term for that? 

Here is the link to the instrument manual: https://www.kippzonen.com/Download/52/CM-21-Pyranometer-Manual

**Comment by JordanAthertonNOC** [comment]
Hi @snionbaven, @snehalprabhu10 

One new term has been created and will be published online tomorrow as follows:
Kipp and Zonen CM21 pyranometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2084/)
