### ISSUE TITLE
NTR: Trimble BX982 Receiver Enclosure [BODCNVS-2191]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#249]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Trimble

## Device range
BX

## Device model
BX982

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'multi-channel','multi-frequency',

## Instrument type
OEM GNSS Receiver Enclosure

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://oemgnss.trimble.com/en/products/receiver-enclosures/bx982

## Mapping to external terminologies (optional)
n/a

**Comment by JordanAthertonNOC** [comment]
Hi @snionbaven, @snehalprabhu10 

One new term has been created and will be published online tomorrow as follows:
Trimble BX982 GNSS beacon receiver enclosure (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2085/)
