### ISSUE TITLE
NTR: Trimble SPS356 L1 GNSS Beacon Receiver [BODCNVS-2193]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#251]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Trimble

## Device range
n/a

## Device model
SPS356

## Model version
L1

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'multi-constellation','positioning','wifi-monitoring'

## Instrument type
GNSS Beacon Receiver

## Does the tool describe a series of instruments? 
Individual 

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://heavyindustry.trimble.com/en/products/gnss-receivers-and-antennas-marine-construction

## Mapping to external terminologies (optional)
n/a

**Comment by JordanAthertonNOC** [comment]
Hi @snionbaven

One new term has been created and will be published online tomorrow as follows:
Trimble SPS356 GNSS beacon receiver (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2086/)
