### ISSUE TITLE
NTR: Furuno DS60 Doppler Sonar [BODCNVS-2194]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#252]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Furuno

## Device range
DS
## Device model
DS60
## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'3-axis','precision','berthing-and-docking'

## Instrument type
Doppler Sonar

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://www.furuno.com/files/Brochure/161/upload/ds-60.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
n/a

**Comment by JordanAthertonNOC** [comment]
Hi @snionbaven 

This term has now been created and is queued for publication on the NVS tomorrow morning at ~07:00 GMT
Furuno DS-60 Doppler sonar (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2074/)
