### ISSUE TITLE
NTR: Teledyne Benthos UTS 9400 Universal Deck Box [BODCNVS-2195]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#253]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Teledyne Benthos

## Device range
9000
## Device model
9400

## Model version
n/a
## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'single-unit'

## Instrument type
Universal Deck Box
## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://www.sikuliaq.alaska.edu/ops/pdf/Benthos_UDB9400E_deck_box_datasheet_1.pdf

## Mapping to external terminologies (optional)
n/a

**Comment by danibodc** [comment]
This term has now been loaded to L22: 
TOOL2089 - Teledyne Benthos UDB-9400 Universal Deck Box 

It will be live on the NVS from tomorrow morning at https://vocab.nerc.ac.uk/collection/L22/current/TOOL2089.
