### ISSUE TITLE
NTR: AML Oceanographic CXchange Conductivity Sensor [BODCNVS-2196]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#254]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
AML Oceanographic

## Device range
Xchange

## Device model
C

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'field-swappable','compact'

## Instrument type
Conductivity Sensor

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://www.subseatechnologies.com/aml-oceanographic/xchange-sensor-heads/

## Mapping to external terminologies (optional)
n/a

**Comment by danibodc** [comment]
Hi @snionbaven this term already exists in L22: https://vocab.nerc.ac.uk/collection/L22/current/TOOL1522/
