### ISSUE TITLE
NTR: Seabird Scientific ECO-FL-RTD Fluorometer [BODCNVS-2197]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#255]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Seabird Scientific

## Device range
ECO

## Device model
ECO-FL-RTD

## Model version
n/a

## Model alternative name (if applicable)
ECO Fluorometer

## Modification (if applicable)
n/a

## Qualification (if applicable)
'real-time-deep','wide-range','high-resolution'

## Instrument type
Fluorometer

## Does the tool describe a series of instruments? 
Individual 

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://www.seabird.com/eco-fluorometer/product?id=60429374754

## Mapping to external terminologies (optional)
n/a

**Comment by JordanAthertonNOC** [comment]
Hi @snionbaven 

I believe this one already exists here: 
https://vocab.nerc.ac.uk/collection/L22/current/TOOL1439/

All of our Sea-Bird sensors are now prefixed with `WET Labs {Sea-Bird WETLabs}` for consistency, and to try and capture searches for both `WET Labs` and `WETLabs` (we couldn't expand this further for `Sea-Bird` and `Seabird` though unfortuantely
