### ISSUE TITLE
NTR: R.M. Young Company 85004 Ultrasonic Anemometer (Heated) [BODCNVS-2198]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#256]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
R.M. Young Company

## Device range
n/a

## Device model
85004

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'heated','wind-sensor'

## Instrument type
Ultrasonic Anemometer

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://www.youngusa.com/wp-content/uploads/2020/01/85004-90G.pdf

## Mapping to external terminologies (optional)
n/a

**Comment by jakjonbodc** [comment]
TOOL2081 - RM Young 85004 (heated) ultrasonic anemometer
https://vocab.nerc.ac.uk/collection/L22/current/TOOL2081/
