### ISSUE TITLE
NTR: Paroscientific, Inc MET4A Meteorological Measurement System [BODCNVS-2199]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#257]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Paroscientific, Inc

## Device range
MET

## Device model
MET4A

## Model version
A

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'fan-aspirated'

## Instrument type
Meteorological Measurement System

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
MET4A

## Documentation
https://paroscientific.com/pdf/8008-001_Manual_for_MET4_and_MET4A_Meteorological_Measurement_Systems.pdf

## Mapping to external terminologies (optional)
n/a

**Comment by jakjonbodc** [comment]
Term is now live on NVS:
https://vocab.nerc.ac.uk/collection/L22/current/TOOL2082/
TOOL2082 - Paroscientific MET4A (fan-aspirated) meteorological measurement system
