### ISSUE TITLE
NTR: AXIS Communications M1054 Network Camera [BODCNVS-2217]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#260]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
AXIS Communications

## Device range
M

## Device model
M1054

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
Network Camera

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
n/a

## Documentation
https://www.axis.com/products/axis-m1054/support#support-resources

## Mapping to external terminologies (optional)
n/a

**Comment by jakjonbodc** [comment]
Term is live on NVS:
TOOL2088 - Axis Communications M1054 network camera
https://vocab.nerc.ac.uk/collection/L22/current/TOOL2088/
