### ISSUE TITLE
NTR: Hemisphere GNSS Vector V104 GPS Compass [BODCNVS-2218]

### ISSUE THREAD

**Issue by snionbaven** [nvs-vocabs/L22#261]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Hemisphere GNSS

## Device range
Vector

## Device model
Vector V104

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
'differential-gps','low-profile','multi-path'

## Instrument type
GPS Compass

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
Vector V104

## Documentation
https://www.subseatechnologies.com/hemisphere-gnss/position-and-heading-receivers/v104/

## Mapping to external terminologies (optional)
n/a

**Comment by JordanAthertonNOC** [comment]
One new term created, this is now live on the NVS:
http://vocab.nerc.ac.uk/collection/L22/current/TOOL2090/
Hemisphere GNSS V104 GPS Compass
