### ISSUE TITLE
NTR: Sonardyne Nano [BODCNVS-2228]

### ISSUE THREAD

**Issue by snehalprabhu10** [nvs-vocabs/L22#264]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Sonardyne Nano

## Device range
USBL 

## Device model
Sonardyne Nano

## Model version
n/a

## Model alternative name (if applicable)
Nano

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
USBL transponder

## Does the tool describe a series of instruments? 
Individual

## Reference (if applicable)
n/a

## Short name
Nano

## Documentation
https://www.sonardyne.com/products/nano-small-rov-auv-diver-tracking/

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by JordanAthertonNOC** [comment]
One new term has been created and will be published online tomorrow as follows:
Sonardyne Nano transponder series (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2092/)
