### ISSUE TITLE
NTR: Sonardyne DPT 6 [BODCNVS-2226]

### ISSUE THREAD

**Issue by snehalprabhu10** [nvs-vocabs/L22#266]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Sonardyne

## Device range
n/a

## Device model
DPT 6

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
USBL

## Does the tool describe a series of instruments? 
[Does the term describe a manufacturing 'series' of instruments, a 'system' of instruments, an 'individual' instrument or other?]

## Reference (if applicable)
n/a

## Short name
DPT 6

## Documentation
https://www.sonardyne.com/wp-content/uploads/2021/06/Sonardyne_8301_dpt6.pdf

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by JordanAthertonNOC** [comment]
One new term has been created and will be published online tomorrow as follows:
Sonardyne Dynamic Positioning Transponder 6 series (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2091/)
