### ISSUE TITLE
NTR: Flow through analyser of total alkalinity [BODCNVS-2235]

### ISSUE THREAD

**Issue by lmerchant** [nvs-vocabs/L22#267]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
[This is the name of the manufacturer or institution which made the instrument. If there is a manufacturer but you have not been able to confirm this information or there is no official manufacturer, input 'Inapplicable'. If you are creating a generic instrument (e.g. a generic temperature sensor, then input 'Unspecified'.]

4H-JENA engineering GmbH

https://www.4h-jena.de/en/company/about-us/

## Device range
[The manufacturer's instrument model range (e.g. WindObserver). If there is no official model range then input 'n/a'.]

n/a

## Device model
[Name of the instrument model. If there is no official model name, input 'n/a'.]

CONTROS HydroFIA® TA

## Model version
[Name of the sub-model (e.g. 'D', 'v3.2'). If there is no official version/sub-model then input 'n/a'.]

n/a

## Model alternative name (if applicable)
[Alternative name for the model. E.g. Glider Payload CTD alternative name is GPCTD]

n/a

## Modification (if applicable)
[Describes any modifications to the instrument design, such as a manufactured device that has been modified 'in-house' or a plakton net that has been modified since its first description.]

n/a

## Qualification (if applicable)
[Qualification of the instrument type i.e. a word or words that further describe the instrument type (e.g. 'portable','automated','pressure-compensated','large' etc.). Sometimes these are used in manufacturer names.]

FEATURES

Measurement cycles of less than 10 min
Robust pH determination using absorption spectrometry
Single-point titration
Low sample consumption (<50 ml)
Low reagent consumption (100 μL)
User-friendly “Plug and Play” reagent cartridges
Minimized biofouling effects due to acidification of the sample
Autonomous long-term installations

## Instrument type
[Please indicate what type of instrument it is (e.g. global positioning system, fluorometer, etc.)]

Flow through analyzer of total alkalinity of seawater.

Company description:
The CONTROS HydroFIA® TA is a flow through system for the determination of the total alkalinity in seawater.  It can be used for continuous monitoring during surface water applications as well as for discrete sample measurements. It measures pH using absorption spectrometry.

## Does the tool describe a series of instruments? 
[Does the term describe a manufacturing 'series' of instruments, a 'system' of instruments, an 'individual' instrument or other?]

individual instrument

## Reference (if applicable)
[Citation for the instrument (e.g. Hall and Bumpus 1937, 1944). Use if the instrument is manufactuered and built according to a design in a paper.]

n/a

## Short name
[Shortened name of the instrument. This is usually a shortened version of name limited to make, model and version. It can also be an alternative name.]

TA -Analyzer

## Documentation
[Please enter a link to the documentation describing the instrument. This could be a journal reference, manufacturer data sheet, web site, manual etc.]

company sales page: https://www.4h-jena.de/en/maritime-technologies/sensors/hydrofiarta/

product sheet: https://www.4h-jena.de/wp-content/uploads/2021/11/PS-_CCONTROS-HydroFIA-TA_v1.1.pdf

Applications of instrument: https://www.4h-jena.de/wp-content/uploads/2022/05/AN-_detecting-and-quantifying_v1.1.pdf

Paper on instrument abilities: https://aslopubs.onlinelibrary.wiley.com/doi/10.1002/lom3.10329
 

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

Existing NERC entries for other instruments measuring total alkalinity of seawater

https://vocab.nerc.ac.uk/collection/L22/current/TOOL1851/ (Scripps Institution of Oceanography total alkalinity titration system)

https://vocab.nerc.ac.uk/collection/L22/current/TOOL1014/ (Apollo SciTech AS-ALK2 total alkalinity titrator)

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by danibodc** [comment]
Hi @lmerchant this term has now been loaded and will be live on the NVS from tomorrow morning at https://vocab.nerc.ac.uk/collection/L22/current/TOOL2108.

TOOL2108 - 4H JENA engineering CONTROS HydroFIA TA total alkalinity analyser
