### ISSUE TITLE
Inconsistency in instrument name for L22::TOOL0791

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/L22#27]
@louatbodc A user reported a discrepancy for L22::TOOL0791 where instrument name is 'Teledyne Benthos BFP 213 pinger' but the description refers to an instrument named 'The Teledyne Benthos BFP-312 bottom finding pinger'. The user's own investigation suggest that BFP-312 might be the correct one based on internet search.

**Comment by louatbodc** [comment]
After investigation it was found there was no model 213 and this was deemed to be a typo. The term was updated to reflect model 312.

http://vocab.nerc.ac.uk/collection/L22/current/TOOL0791/

Please note, the update may not appear for on our web services for up to 24 hours.
