### ISSUE TITLE
NTR: Underwater Vision Profiler version 5 StandarD [BODCNVS-2362]

### ISSUE THREAD

**Issue by picheral** [nvs-vocabs/L22#275]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Hydroptic

## Device range
'n/a'

## Device model
Underwater Vision Profiler version 5 (UVP5)

## Model version
Underwater Vision Profiler version 5 StandarD

## Model version definition
The Underwater Vision Profiler version 5 or UVP5 is designed to study particles and zooplankton simultaneously and to quantify them in a known volume of water. The UVP counts and sizes all objects > 100 µm and records images of aggregates and plankton > 700 µm. It is usually operated as a stand-alone system, attached to a CTD-Rosette frame. The UVP5 acquires only in-focus images in a volume of water delimited by a light beam issued from red light-emitting diodes (LEDs) in ~100 µs flashes. The collimated light beam illuminates a sampling volume of ~1 litre per image which are acquired and processed at up to 20Hz. When interfaced with conventional CTD measuring devices, the total abundance of particles can be displayed in real time, integrated with the CTD data. The system has a typical depth range of 6000 m.
UVP5 equipped with a 1.3Mpixel camera (pixel size : 140-184µm)

## Model alternative name (if applicable)
'n/a'

## Modification (if applicable)
'n/a'

## Qualification (if applicable)
'n/a'

## Instrument type
Particle and plankton counter using imagery

## Does the tool describe a series of instruments? 
series

## Reference (if applicable)
https://aslopubs.onlinelibrary.wiley.com/doi/10.4319/lom.2010.8.462

## Short name
UVP5SD

## Documentation
https://aslopubs.onlinelibrary.wiley.com/doi/10.4319/lom.2010.8.462

## Mapping to external terminologies (optional)
'n/a'

## ORCID (optional)
0000-0001-8172-5473

**Comment by roswri** [comment]
Term created and should be live on the NVS tomorrow morning: Hydroptic Underwater Vision Profiler 5 StandarD {UVP5} imaging sensor (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2109/)
