### ISSUE TITLE
NTR: Underwater Vision Profiler version 6 Low Power [BODCNVS-2359]

### ISSUE THREAD

**Issue by picheral** [nvs-vocabs/L22#278]
## Device make
Hydroptic

## Device range
'n/a'

## Device model
Underwater Vision Profiler version 6 (UVP6)

## Model version
Underwater Vision Profiler version 6 Low Power

## Model version definition
The Underwater Vision Profiler version 6 or UVP6 is designed to study particles and zooplankton simultaneously and to quantify them in a known volume of water. The UVP counts and sizes all objects > 60 µm and records images of aggregates and plankton > 620 µm. The UVP6 acquires only in-focus images in a volume of water delimited by a light beam issued from a red laser diode in ~100 µs flashes. The collimated light beam illuminates a sampling volume of ~0.6 litre per image and the pixel size is 73µm. The images can be acquired at up to 20Hz. The UVP6 is a very versatile system weighting 1.6Kg in water and consuming very low power. It has been utilised in long term mooring, cabled observatories, CTD-rosette frames, gliders, AUVs, profiling floats and drifting lines. When interfaced with conventional CTD measuring devices, the total abundance of particles can be displayed in real time, integrated with the CTD data. The system has a typical depth range of 6000 m.
UVP6 fitted with a low power image processor allowing to adjust the mean power ( < 0.8W) according to the acquisition rate ( < 1.3Hz).

## Model alternative name (if applicable)
'n/a'

## Modification (if applicable)
'n/a'

## Qualification (if applicable)
'n/a'
## Instrument type
Particle and plankton counter using imagery

## Does the tool describe a series of instruments? 
series

## Reference (if applicable)
https://aslopubs.onlinelibrary.wiley.com/doi/full/10.1002/lom3.10475

## Short name
UVP6LP

## Documentation
https://aslopubs.onlinelibrary.wiley.com/doi/full/10.1002/lom3.10475

## Mapping to external terminologies (optional)
'n/a'

## ORCID (optional)
0000-0001-8172-5473

**Comment by roswri** [comment]
Hi @picheral,

The description of Hydroptic Underwater Vision Profiler 6 LP {UVP6} imaging sensor on the NVS (https://vocab.nerc.ac.uk/collection/L22/current/TOOL1578/) has been updated as requested, the update should go live early tomorrow morning.
