### ISSUE TITLE
NTR: SBE5 [BODCNVS-2380]

### ISSUE THREAD

**Issue by jnahorniak** [nvs-vocabs/L22#281]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Sea-Bird Scientific

## Device range
n/a

## Device model
SBE 5

## Model version
T (titanium) or P (plastic) housing

## Model alternative name (if applicable)
SBE 5T/5P

## Instrument type
submersible pump

## Does the tool describe a series of instruments? 
individual

## Short name
Sea-Bird Scientific SBE 5T/5P

## Documentation
https://www.seabird.com/sbe-5t-5p-submersible-pump/product?id=60762467710

## Mapping to external terminologies (optional)
http://vocab.nerc.ac.uk/collection/L35/current/MAN0013/

**Comment by JordanAthertonNOC** [comment]
One new term has been created and will be published online tomorrow as follows: 
Sea-Bird SBE 5 submersible pump series (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2120/)
