### ISSUE TITLE
NTR: SMRU GPS phone tags

### ISSUE THREAD

**Issue by robthomas-marine** [nvs-vocabs/L22#37]
[L22_submission_template_v2.2.xlsx](https://github.com/nvs-vocabs/L22/files/5057481/L22_submission_template_v2.2.xlsx)

Request for an L22  addition to cover SMRU GPS phone tags.

**Comment by louatbodc** [comment]
Created:
Sea Mammal Research Unit Fastloc GSM {GSMDL} GPS phone tag (TOOL1523)

Code created to cover one of a couple of models.

Please note, it can take up to 24 hours for new terms to be fully published on our web services.

**Comment by louatbodc** [comment]
tagging @robthomas-marine for information
