### ISSUE TITLE
Implement Kongsberg Maritime CONTROS HydroFlash O2 optode

### ISSUE THREAD

**Issue by hahn-johannes** [nvs-vocabs/L22#38]
Adequately to https://github.com/nvs-vocabs/L22/issues/36, the instrument type "Kongsberg Maritime CONTROS HydroFlash O2 optode" should be implemented in the L22 vocabulary. Is this possible?

The data sheet can be found here:
https://www.kongsberg.com/contentassets/4259c6dfed2d4ae3980fba37ec013ea8/hydroflash-accurate-fast-and-versatile-oxygen-optode.pdf

**Comment by louatbodc** [comment]
Term has been added. Please note it may take up to 24 hours for the term to appear on our web services.

Kongsberg Maritime CONTROS HydroFlash O2 (underwater) oxygen optode (TOOL1540)
