### ISSUE TITLE
NTR: New publication SBE 37 IMP-ODO CTP [BODCNVS-618]

### ISSUE THREAD

**Issue by louatbodc** [nvs-vocabs/L22#40]
A new term was requested via NVS Vocabulary Group email.

Sea-Bird SBE 37 MicroCat IMP-CTP-ODO (submersible) CTD sensor (TOOL1538)

Please note, it may take up to 24 hours for new publications to appear on our web services.

**Comment by roswri** [comment]
Hi @hahn-johannes,

I have now created a term for the Sea-Bird SBE 37 MicroCat IMP-CT-ODO (submersible) CTD sensor (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1545/). Again, it may take up to 24 hours for new publications to appear on our web services.

Best wishes,
Roseanna
