### ISSUE TITLE
NTR: Jumbo Piston Corer

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#42]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Navy Engineering Lab (NEL) from WHOI design

## Device range
n/a

## Device model
n/a

## Model version
n/a

## Model alternative name (if applicable)
JPC

## Modification (if applicable)
n/a

## Qualification (if applicable)
[Qualification of the instrument type i.e. a word or words that further describe the instrument type (e.g. 'portable','automated','pressure-compensated','large' etc.). Sometimes these are used in manufacturer names.]

## Instrument type
corer

## Does the tool describe a series of instruments? 
no

## Short name
JPC

## Documentation
https://www.usgs.gov/centers/pcmsc/science/jumbo-piston-corer?qt-science_center_objects=0#qt-science_center_objects

## Mapping to external terminologies (optional)
BCODMO/519 

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by roswri** [comment]
Hello,

I have created the new term for this: Navy Engineering Lab (NEL) from WHOI design jumbo piston corer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1560/). Please note the link may take up to 24 hours to go live on the website. Let me know if there is any issues with the term, we can re-open the ticket and make any necessary updates.

Best wishes,
Roseanna
