### ISSUE TITLE
NTR: In situ ichthyoplankton imaging system (ISIIS)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#43]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Collaboration with BellaMare LLC and University of Miami RSMAS 

## Device range
n/a

## Device model
n/a

## Model version
n/a

## Model alternative name (if applicable)
ISIIS

## Modification (if applicable)
n/a

## Qualification (if applicable)
[Qualification of the instrument type i.e. a word or words that further describe the instrument type (e.g. 'portable','automated','pressure-compensated','large' etc.). Sometimes these are used in manufacturer names.]

## Instrument type
Imaging System

## Does the tool describe a series of instruments? 
n/a

## Reference (if applicable)
Robert Cowen, Cedric Guigand. In situ ichthyoplankton imaging system (ISIIS): system design and preliminary results. https://doi.org/10.4319/lom.2008.6.126

## Short name
ISIIS

## Documentation
https://www.planktonimaging.com/

**Comment by roswri** [comment]
Hello,

I have created the new term for this: BellaMare LLC and University of Miami RSMAS In Situ Ichthyoplankton Imaging System {ISIIS} - Cowen and Guigand (2008) (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1561/). Please note the link may take up to 24 hours to go live on the website. Let me know if there is any issues with the term, we can re-open the ticket and make any necessary updates.

Best wishes,
Roseanna
