### ISSUE TITLE
NTR: Submersible Ultraviolet Nitrate Analyser V2

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#44]
Please provide the following information (all fields are mandatory unless specified otherwise)
Previous instrument was manufactured by Satlantic SUNA (probably V1).

## Device make
SeaBird

## Device range
n/a

## Device model
SUNA

## Model version
V2

## Model alternative name (if applicable)
SUNAV2

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a]

## Instrument type
nutrient analyzer

## Does the tool describe a series of instruments? 
yes..several different choices 10mm/5mm pathlength; freshwater/saltwater/class-based freshwater; 500m/100m depth; 2Gb/none data storage; anti-fouling wiper.

## Reference (if applicable)
n/a

## Short name
SUNAV2

## Documentation
https://www.seabird.com/nutrient-sensors/suna-v2-nitrate-sensor/family?pageSize=50&sortBy=sequence&productCategoryId=54627869922&secondPageNumber=1&hideObsolete=true&pimContext=SeabirdUSen&erpSystem=SITE_ADMIN&focusResults=true

## Mapping to external terminologies (optional)
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

## ORCID (optional)
[Enter your ORCID if desired]

**Comment by roswri** [comment]
Hello,

I have created the new term for this: Satlantic Submersible Ultraviolet Nitrate Analyser V2 {SUNA V2} nutrient analyser series (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1562/). Please note the link may take up to 24 hours to go live on the website. Let me know if there is any issues with the term, we can re-open the ticket and make any necessary updates.

Best wishes,
Roseanna
