### ISSUE TITLE
NTR: Kongsberg EM712

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#45]
## Device make
Kongsberg 

## Device range
EM

## Device model
712
## Model version
n/a

## Instrument type
multibeam echosounder

## Does the tool describe a series of instruments? 
No

## Short name
Kongsberg EM712

## Documentation
https://www.kongsberg.com/maritime/products/mapping-systems/mapping-systems/multibeam-echo-sounders/em-712-multibeam-echosounder-max.-3600-m/

## Mapping to external terminologies (optional)
Broader | http://vocab.nerc.ac.uk/collection/L05/current/157/
Related | http://vocab.nerc.ac.uk/collection/B75/current/ORG00360/

## ORCID (optional)
https://orcid.org/0000-0001-6840-6785

**Comment by roswri** [comment]
Hi @botheredbybees ,

This new term has now been created and is live on the website: Kongsberg EM 712 multibeam echosounder (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1601/)

Best wishes,
Roseanna
