### ISSUE TITLE
NTR: Simrad MS70

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#46]
## Device make
Kongsberg

## Device range
MS

## Device model
70

## Model version
n/a

## Model alternative name (if applicable)
Simrad

## Instrument type
multibeam echosounder

## Short name
Simrad MS70

## Documentation
https://www.kongsberg.com/maritime/products/mapping-systems/fishery-research/scientific-multibeam-systems/simrad-ms70/

## Mapping to external terminologies (optional)
Broader | http://vocab.nerc.ac.uk/collection/L05/current/157/
Related | http://vocab.nerc.ac.uk/collection/B75/current/ORG01511/
Related | http://vocab.nerc.ac.uk/collection/B75/current/ORG00360/

## ORCID (optional)
https://orcid.org/0000-0001-6840-6785

**Comment by roswri** [comment]
Hi @botheredbybees ,

This new term has now been created and is live on the website: Kongsberg (Simrad) MS70 multibeam echosounder (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1602/)

Best wishes,
Roseanna
