### ISSUE TITLE
NTR: SAL T2+ Speed Log

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#47]
## Device make
Consilium

## Device range
SAL

## Device model
T2

## Model version
n/a

## Model alternative name (if applicable)
SAL T2+ Acoustic Correlation Dual Speed Log

## Qualification (if applicable)
plus (+)

## Instrument type
Doppler speed log

## Does the tool describe a series of instruments? 
individual

## Short name
SAL T2+

## Documentation
https://www.consilium.ae/business-areas/marine/products/speed-log-echo-sounders/#SAL-T2PLUS

## Mapping to external terminologies (optional)
Broader | http://vocab.nerc.ac.uk/collection/L05/current/114/

## ORCID (optional)
https://orcid.org/0000-0001-6840-6785

**Comment by danibodc** [comment]
We have now created:

TOOL1669 - Consilium SAL T2+ acoustic correlation dual speed log (https://vocab.nerc.ac.uk/collection/L22/current/TOOL1669)

Please note the URL will not become live on the NVS until tomorrow morning after the database refresh.

Many thanks.
