### ISSUE TITLE
NTR: Seapath 380

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#48]
## Device make
Kongsberg 

## Device range
Seapath 

## Device model
380

## Model alternative name (if applicable)
Seapath 380 series Ultimate heading, attitude and positioning sensor

## Instrument type
Heading, Attitude and Positioning Sensor

## Short name
Kongsberg Seapath 380

## Documentation
https://www.kongsberg.com/globalassets/maritime/km-products/product-documents/seapath-380---utilising-gps-glonass-galileo-beidou-and-qzss

## Mapping to external terminologies (optional)

Broader | http://vocab.nerc.ac.uk/collection/L05/current/POS04/
Broader | http://vocab.nerc.ac.uk/collection/L05/current/POS02/
Broader | http://vocab.nerc.ac.uk/collection/L05/current/POS19/
Related | http://vocab.nerc.ac.uk/collection/B75/current/ORG00360/

## ORCID (optional)
https://orcid.org/0000-0001-6840-6785

**Comment by vpaba** [comment]
Hello,

Thanks for your patience! The requested term has now been created: https://vocab.nerc.ac.uk/collection/L22/current/TOOL1623/.

Please note that the link may take up to 24 hours to go live on the website.
We're happy to re-open the issue to address any questions you may have.

Kind regards,

Violetta
