### ISSUE TITLE
NTR: Bulk term request

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#49]
Bulk submission: RSV Nuyina instruments
[L22_submission_Nuyina.xlsx](https://github.com/nvs-vocabs/L22/files/5544079/L22_submission_Nuyina.xlsx)

**Comment by JordanAthertonNOC** [comment]
Hi @botheredbybees 

Five new instruments have been created and are now live:

Kongsberg Simrad SH90 fish finding sonar (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1683/)
Kongsberg HiPAP 102 Ultra Short BaseLine acoustic positioning system (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1684/)
Teledyne Reson SeaBat T20 R multibeam echosounder (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1685/)
Vaisala WINDCAP WMT700 ultrasonic anemometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1686/)
Vaisala HUMICAP HMP155 Humidity and Temperature Probe (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1687/)

Many thanks
