### ISSUE TITLE
NTR: Solar Radiation Sensor Model CMP3

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#50]
## Device make
Kipp and Zonen

## Device range
Solar Radiation Sensor

## Device model
CMP3

## Model version
n/a

## Model alternative name (if applicable)
CMP3 pyranometer

## Instrument type
pyranometer

## Does the tool describe a series of instruments? 
individual

## Short name
Kipp and Zonen CMP3 pyranometer

## Documentation
https://www.kippzonen.com/Product/11/CMP3-Pyranometer#.X7Q89WhLhZc

## Mapping to external terminologies (optional)
Broader | http://vocab.nerc.ac.uk/collection/S04/current/S04300/

## ORCID (optional)
https://orcid.org/0000-0001-6840-6785

**Comment by roswri** [comment]
Hi @botheredbybees ,

Your new term has now been created: Kipp and Zonen CMP3 pyranometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1604/)

The new term has been queued for publication but is not yet live. We currently have only one publication round per day and the next one will be shortly after 0700UT (AM) tomorrow.

Best wishes,
Roseanna
