### ISSUE TITLE
NTR: CUV5 Total UV Radiometer

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#51]
## Device make
Kipp and Zonen

## Device range
n/a

## Device model
CUV5

## Model version
n/a

## Model alternative name (if applicable)
CUV5 Total UV Radiometer

## Instrument type
Radiometer

## Does the tool describe a series of instruments? 
individual

## Short name
Kipp and Zonen CUV5 ultraviolet Radiometer

## Documentation
https://www.kippzonen.com/Product/163/CUV5-Total-UV-Radiometer#.X7Q_BmhLhZc

## Mapping to external terminologies (optional)
Broader | http://vocab.nerc.ac.uk/collection/L05/current/122/
Related | http://vocab.nerc.ac.uk/collection/B75/current/ORG00325/

## ORCID (optional)
https://orcid.org/0000-0001-6840-6785

**Comment by roswri** [comment]
Hi @botheredbybees ,

I have created your new term: Kipp and Zonen CUV5 Total UV Radiometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1598/)

The new term has been queued for publication but is not yet live. We currently have only one publication round per day and the next one will be shortly after 0700UT (AM) tomorrow.

Best wishes,
Roseanna
