### ISSUE TITLE
NTR: Solar light 501 UV radiometer

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#54]
## Device make
Solar Light

## Device range
n/a

## Device model
501

## Qualification (if applicable)
biometer

## Instrument type
radiometer

## Does the tool describe a series of instruments? 
individual

## Short name
501 UV Biometer Radiometer

## Documentation
https://solarlight.com/product/uvb-biometer-model-501-radiometer/

## Mapping to external terminologies (optional)
Broader | http://vocab.nerc.ac.uk/collection/L05/current/122/
Related | http://vocab.nerc.ac.uk/collection/L22/current/TOOL0812/

## ORCID (optional)
https://orcid.org/0000-0001-6840-6785

**Comment by roswri** [comment]
Hi @botheredbybees ,

I have created the new term: Solar Light 501 (biometer) radiometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1643)

Let me know if there are any issues.

Best wishes,
Roseanna
