### ISSUE TITLE
NTR: PhytoFlash fluorometer

### ISSUE THREAD

**Issue by botheredbybees** [nvs-vocabs/L22#56]
## Device make
Turner designs

## Device range
n/a

## Device model
PhytoFlash

## Model version
n/a

## Model alternative name (if applicable)
[Alternative name for the model. E.g. Glider Payload CTD alternative name is GPCTD]

## Qualification (if applicable)
in situ variable fluorescence system

## Instrument type
fluorometer

## Does the tool describe a series of instruments? 
no

## Short name
PhytoFlash

## Documentation
https://www.turnerdesigns.com/phytoflash-active-fluorometer

## ORCID (optional)
https://orcid.org/0000-0001-6840-6785

**Comment by roswri** [comment]
Hi @botheredbybees ,

Your new term has now been created: Turner Designs PhytoFlash [submersible] active fluorometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1603/)

The new term has been queued for publication but is not yet live. We currently have only one publication round per day and the next one will be shortly after 0700UT (AM) tomorrow.

Best wishes,
Roseanna
