### ISSUE TITLE
Bulk New Term Request (BODNVS-1011)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#57]
Attaching template for bulk submission of terms. 

[20200813_L22_submission.xlsx](https://github.com/nvs-vocabs/L22/files/5696853/20200813_L22_submission.xlsx)

**Comment by roswri** [comment]
Hi @rhudak2020 ,

We are nearly done creating terms. I just have a quick question about the 'Dynamic Gravity Systems AT1 gravimeter', I assume this is the marine version, could you confirm?

Many thanks,
Roseanna

**Comment by rhudak2020** [comment]
Hi @roswri,

Yes the Gravimeter is a marine version/installation. Thank you.

Rebecca

**Comment by louatbodc** [comment]
Thank you for your request. I'm pleased to say we have now completed the publication of terms. The terms can be viewed here:

https://github.com/nvs-vocabs/L22/issues/170

Many thanks
Lou
