### ISSUE TITLE
Request for clarification: L22 terms for cameras

### ISSUE THREAD

**Issue by mcuthill** [nvs-vocabs/L22#58]
I've been struggling with the question: do cameras belong in the L22 vocabulary? Judging by the fact that there are only about 20 L22 terms for camera models, it seems there's some ambivalence in the community about whether they're appropriate or not, or if so what types. 

Has there been any discussion of this, or consensus on best practices?

**Comment by danibodc** [comment]
Thanks for your question. As you say, only a few cameras have currently been created under L22, not for any reason such as ambivalence in the community. We envision that more will be added in the future as the use of cameras on ROVs and AUVs for instance increases, as well as the use of handheld cameras such as GoPros, and even smartphone devices etc.

Earlier this year we discussed the broadening of the L05 instrument category terms for cameras (see https://github.com/nvs-vocabs/L05/issues/9), and we combined them into the single category 'cameras' to cover all types.

We believe there is potential for different types of camera to be added to L22, and mapped to the L05 term 'cameras', as they can be used in many different ways and in many different configurations to produce video and imagery data, for a number of applications.
