### ISSUE TITLE
NTR: AML-6 multiparameter sonde

### ISSUE THREAD

**Issue by mcuthill** [nvs-vocabs/L22#59]
## Device make
AML Oceanographic

## Device range
AML-6

## Device model
LGR

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
multiparameter

## Instrument type
sonde

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
AML-6 LGR

## Documentation
https://amloceanographic.com/product/aml-6/ 

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
n/a

**Comment by vpaba** [comment]
Hello,

The requested term has now been created: http://vocab.nerc.ac.uk/collection/L22/current/TOOL1599/. 
Please note that the link may take up to 24 hours to go live on the website. 

We're happy to re-open the issue to address any questions you may have.

Thanks and kind regards,

Violetta
