### ISSUE TITLE
NTR: Star-Oddi DST-CT (BODCNVS-879)

### ISSUE THREAD

**Issue by robthomas-marine** [nvs-vocabs/L22#60]
[L22_submission_template_v2.2_StarOddiDST-CT.xlsx](https://github.com/nvs-vocabs/L22/files/5926604/L22_submission_template_v2.2_StarOddiDST-CT.xlsx)
Request for a new term for a Star-Oddi DST-CT attached.

**Comment by robthomas-marine** [comment]
Hi,

Is there a timetable for when this term might be added? 

Currently have data for EMODNet Ingestion on-hold until this term is added.

Cheers
Rob

**Comment by gwemon** [comment]
Hi @robthomas-marine It looks like this term was added to the NVS on 10th March but the person who made the update forgot to update the github ticket and notify you. Our apologies! 
This is the new term in the NVS: https://vocab.nerc.ac.uk/collection/L22/current/TOOL1648/
