### ISSUE TITLE
NTR: AML-1 RT

### ISSUE THREAD

**Issue by mcuthill** [nvs-vocabs/L22#61]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
AML Oceanographic

## Device range
n/a

## Device model
AML-1

## Model version
RT

## Instrument type
sonde

## Does the tool describe a series of instruments? 
individual

## Short name
AML-1 RT

## Documentation
https://amloceanographic.com/product/aml-1-rt/

**Comment by roswri** [comment]
Hi @mcuthill,

I have now made your new term: AML Oceanographic AML-1 RT sonde (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1646/)

The new term has been queued for publication but is not yet live. We currently have only one publication round per day and the next one will be shortly after 0700UT (AM) tomorrow.

Best wishes,
Roseanna
