### ISSUE TITLE
NTR: Apollo SciTech AS-P3

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#62]
## Device make
Apollo SciTech

## Device range
n/a

## Device model
AS-P3

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
pCO2 system

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
AS-P3

## Documentation
http://www.apolloscitech.com/pco2.html#:~:text=Apollo%20SciTech%27s%20Underway%20pCO2,salinity%2C%20temperature%2C%20and%20position.

## Mapping to external terminologies (optional)
https://www.bco-dmo.org/instrument/676

## ORCID (optional)
0000-0002-0017-8330

**Comment by louatbodc** [comment]
The following term has now been published. Please note - it may take up to 24 hours for new terms to appear on our web services.

Apollo SciTech AS-P3 combined pCO2 analyser and underway system (TOOL1674)
