### ISSUE TITLE
NTR: Biospherical QCR-2150 

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#63]
## Device make
Biospherical Instruments Inc

## Device range
QCR

## Device model
2150

## Model version
a fourth‐generation scalar PAR sensor (first gen QSR‐2100 model)

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
digital output

## Instrument type
PAR sensor 

## Does the tool describe a series of instruments? 
series of instruments

## Reference (if applicable)
n/a

## Short name
QCR-2150

## Documentation
http://www.biospherical.com/images/pdf/qsr2150_2013.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by danibodc** [comment]
We have ow created:

TOOL1671 - Biospherical QCR-2150 surface PAR sensor (https://vocab.nerc.ac.uk/collection/L22/current/TOOL1671)

Please note the link above will not become live on the NVS until tomorrow morning after the database refresh.

Many thanks.
