### ISSUE TITLE
NTR: Kipp and Zonen SGR4

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#64]
## Device make
Kipp and Zonen

## Device range
SGR

## Device model
SGR4

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
pyrgeometer

## Does the tool describe a series of instruments? 
individual instrument

## Reference (if applicable)
n/a

## Short name
SGR4

## Documentation
https://www.kippzonen.com/Product/362/SGR4-Pyrgeometer#.YDfYbJP7TAN

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by louatbodc** [comment]
The following term has been published. Please be aware it may take up to 24 hours for the new term to appear on our web services.

Kipp and Zonen SRG 4 pyrgeometer (TOOL1672)
