### ISSUE TITLE
NTR: Kipp and Zonen SMP21

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#65]
## Device make
Kipp and Zonen

## Device range
n/a

## Device model
SMP21

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
analog

## Instrument type
pyranometer

## Does the tool describe a series of instruments? 
individual instrument

## Reference (if applicable)
n/a

## Short name
SMP21

## Documentation
https://www.kippzonen.com/Product/359/SMP21-Pyranometer#.YDfZsZP7TAN

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by danibodc** [comment]
We have now created:

TOOL1670 - Kipp and Zonen SMP21 pyranometer (https://vocab.nerc.ac.uk/collection/L22/current/TOOL1670)

Please note the above URL will not become live until tomorrow morning after the database refresh.

Many thanks.
