### ISSUE TITLE
NTR: Picarro G2401

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#72]
## Device make
Picarro

## Device range
n/a

## Device model
G2401

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
Analyzer

## Instrument type
Spectrometer

## Does the tool describe a series of instruments? 
n/a

## Reference (if applicable)
n/a

## Short name
G2401

## Documentation
http://cires1.colorado.edu/jimenez-group/Manuals/PicarroG2401_Manual_rev_1_14_11.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by roswri** [comment]
Hi @rhudak2020 ,

I have now created the new term::
Picarro G2401 gas analyser (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1677/)

The new term has been queued for publication but is not yet live. We currently have only one publication round per day and the next one will be shortly after 0700UT (AM) tomorrow.

Many thanks,
Roseanna
