### ISSUE TITLE
NTR: RMR CO ROSR (BODCNVS-987)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#73]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Remote Measurements and Research Company (RMR CO)

## Device range
n/a

## Device model
Remote Ocean Surface Radiometer 

## Model version
n/a

## Model alternative name (if applicable)
ROSR

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
radiometer (produces 'sea-surface skin temperature')

## Does the tool describe a series of instruments? 
n/a

## Reference (if applicable)
n/a

## Short name
ROSR

## Documentation
[ROSR_HANDBOOK_v11x.pdf](https://github.com/nvs-vocabs/L22/files/6306989/ROSR_HANDBOOK_v11x.pdf)

## Mapping to external terminologies (optional)
http://vocab.nerc.ac.uk/collection/L22/current/TOOL1526/

## ORCID (optional)
0000-0002-0017-8330

**Comment by JordanAthertonNOC** [comment]
Hi @rhudak2020 

One new code has been created as follows, this will be pushed to live on the NVS at ~0730 UTC tomorrow morning:
Remote Measurements and Research Company Remote Ocean Surface Radiometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1694/)

Best regards

Jordan
