### ISSUE TITLE
Typo of L22:TOOL1672

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#74]
The current listing of L22:TOOL1672 is Kipp and Zonen SRG 4 pyrgeometer.

This is a typo, it should be Kipp and Zonen **SGR 4** pyrgeometer.

**Comment by JordanAthertonNOC** [comment]
Hi @rhudak2020 

Thanks for the report. TOOL1672 has now been updated accordingly. This will be pushed to live on the NVS at ~0730 UTC tomorrow morning.

Best regards

Jordan
