### ISSUE TITLE
NTR: Vaisala WXT536 (BODCNVS-1035)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#80]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Vaisala

## Device range
WXT

## Device model
536

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
weather station

## Does the tool describe a series of instruments? 
WXT530 series

## Reference (if applicable)
n/a

## Short name
WXT536

## Documentation
https://www.vaisala.com/en/products/weather-environmental-sensors/weather-transmitter-wxt530-series

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by danibodc** [comment]
We have now created a term for the Vaisala WXT530 series. This includes the WXT531 (rainfall), WXT532 (wind speed and direction), WXT533 (rainfall, wind speed and direction), WXT534 (air pressure, temperature, humidity) WXT535 (air pressure, temperature, humidity, rainfall) and WXT536 (all above parameters).

TOOL1730 - Vaisala WXT530 weather transmitter series 

This term will be available at https://vocab.nerc.ac.uk/collection/L22/current/TOOL1730 from 0730 UTC tomorrow morning.
