### ISSUE TITLE
NTR: Biospherical QCP-2150 (BODCNVS-1036)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#81]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Biospherical

## Device range
QCP

## Device model
2150

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
radiometer

## Does the tool describe a series of instruments? 
QCP series

## Reference (if applicable)
n/a

## Short name
QCP-2150

## Documentation
http://www.biospherical.com/images/pdf/qcp2150_apr2014.pdf

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by danibodc** [comment]
I have now loaded the following term:

TOOL1737: Biospherical Instruments QCP-2150 [underwater] PAR sensor (https://vocab.nerc.ac.uk/collection/L22/current/TOOL1737)

It will available live on the NVS from 0730 UTC tomorrow morning.
