### ISSUE TITLE
NTR: Valeport VA500 (BODCNVS-1037)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#82]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Valeport

## Device range
n/a

## Device model
VA500

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
altimeter

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
VA500

## Documentation
https://www.valeport.co.uk/products/va500-altimeter/

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by danibodc** [comment]
I have now loaded the following term:

TOOL1738: Valeport VA500 altimeter (https://vocab.nerc.ac.uk/collection/L22/current/TOOL1738)

This will be live on the NVS from 0730 UTC tomorrow morning.
