### ISSUE TITLE
NTR: RM Young 86000 (BODCNVS-1038)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#83]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
RM Young

## Device range
n/a

## Device model
86000

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
ultrasonic anemometer

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
Young 86000

## Documentation
http://www.youngusa.com/products/11/69.html

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by JordanAthertonNOC** [comment]
Hi @rhudak2020 

I have created the new L22 term for this request:
RM Young 86000 ultrasonic anemometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1739/)
This should be pushed to the vocab server and appear online overnight.

Best regards

Jordan
