### ISSUE TITLE
NTR: Kongsberg EM304

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#90]
## Device make
Kongsberg

## Device range
EM

## Device model
304

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
multibeam

## Does the tool describe a series of instruments? 
no

## Reference (if applicable)
[Citation for the instrument (e.g. Hall and Bumpus 1937, 1944). Use if the instrument is manufactuered and built according to a design in a paper.]

## Short name
EM304

## Documentation
https://www.kongsberg.com/maritime/products/ocean-science/mapping-systems/multibeam-echo-sounders/em-304-multibeam-echosounder-max.-8000-m

## Mapping to external terminologies (optional)
n/a

## ORCID (optional)
0000-0002-0017-8330

**Comment by JordanAthertonNOC** [comment]
Hi @rhudak2020

I have created the new L22 term for this request:
Kongsberg EM 304 multibeam echosounder (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1763/)
This should be pushed to the vocab server and appear online overnight.

Best regards

Jordan
