### ISSUE TITLE
NTR: Blue Spirit Liquid Thermometer

### ISSUE THREAD

**Issue by fcarvalhopacheco** [nvs-vocabs/L22#91]
## Device make
[Thermco](https://www.thermcoproducts.com)

## Device range
 n/a

## Device model
Manufacturer Part #: ACC091CBLS
SECO Part #: TMC-ACC091CBLS

## Model version
ASTM Class: S91C

## Model alternative name (if applicable)
Thermco® Products Blue Spirit Filled Thermometer

## Modification (if applicable)
n/a

## Qualification (if applicable)
Blue Spirit Liquid Thermometer

## Instrument type
Thermometer 

## Does the tool describe a series of instruments? 
individual

## Reference (if applicable)
n/a

## Short name
Blue Spirit Thermometer

## Documentation
Link 1 - https://www.thermcoproducts.com/documents/Thermco-2018-ASTM-API-Catalog.pdf

Brand: Thermco
Temperature Range: 20 to 50°C
Thermometer Fill: Blue Spirit
Immersion Type:Partial
Immersion Depth: 76mm
Overall Length: 375mm
Certifications/Compliance: ASTM
ASTM Class: S91C

## Mapping to external terminologies (optional)
http://vocab.nerc.ac.uk/collection/S26/current/MAT00640/
http://vocab.nerc.ac.uk/collection/P06/current/UPAA/
http://vocab.nerc.ac.uk/collection/P07/current/CFSN0381/3/
http://vocab.nerc.ac.uk/collection/P01/current/TEMPPR01/1/
http://vocab.nerc.ac.uk/collection/P25/current/WTEMP/
http://vocab.nerc.ac.uk/collection/P01/current/PSSTTS01/1/
http://vocab.nerc.ac.uk/collection/P10/current/GI000957/1/
http://vocab.nerc.ac.uk/collection/L05/current/134/3/

## ORCID (optional)
https://orcid.org/0000-0002-0376-5338

**Comment by JordanAthertonNOC** [comment]
Hi @fcarvalhopacheco 

I have created the new L22 term for this request:
Thermco Blue Spirit Liquid Thermometer ACC091CBLS (http://vocab.nerc.ac.uk/collection/L22/current/TOOL1744/)
This should be pushed to the vocab server and appear online overnight.

Best regards

Jordan
