### ISSUE TITLE
NTR: Psychro-Dyne Psychrometer

### ISSUE THREAD

**Issue by fcarvalhopacheco** [nvs-vocabs/L22#96]
## Device make
[Industrial Instruments & Supplies](http://www.iisusa.com/Psychro-Dyne-Battery-Operated-Psychrometer-Celsius-BLACK-ORGANIC/productinfo/22012/)

## Device range
°C range: -15 to 45°C

## Device model
n/a
but: Meets federal spec. GG-P-725B, Type III, Style B, NISTCertification available

## Model version
Celsius BLACK ORGANIC

## Model alternative name (if applicable)
Psychro-Dyne Psychrometer

## Modification (if applicable)
n/a

## Qualification (if applicable)
Psychro-Dyne Battery Operated Psychrometer

## Instrument type
Psychrometer

## Does the tool describe a series of instruments? 
It is a completely portable instrument which contains [two thermometers](https://www.coleparmer.com/i/industrial-instruments-80012-replacement-thermometer-15-to-45-c/0331246) that indicates wet and dry bulb temperatures.

## Reference (if applicable)
n/a

## Short name
Psychrometer

## Documentation
Link 1 - http://www.iisusa.com/Psychro-Dyne-Battery-Operated-Psychrometer-Fahrenheit-BLACK-ORGANIC/productinfo/22014/

<p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0in 0in 10pt; padding: 0px; caret-color: rgb(103, 102, 139); color: rgb(103, 102, 139); font-family: Arial; font-size: 14px; text-align: justify;"><span style="line-height: 18.399999618530273px; font-size: 12pt;"><font face="Calibri"><strong style="font-style: normal; font-weight: bold;">SPECIFICATIONS</strong></font></span></p><p style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0px 0px 15px; padding: 0px; caret-color: rgb(103, 102, 139); color: rgb(103, 102, 139); font-family: Arial; font-size: 14px; text-align: justify;"></p>

Psychrometric Tables | 0 to 140°F for relative humidity and dewpoint determination
-- | --
Response Time | 1-1/2 to 2 minutes
Thermometers Length | 8-7/8 in.
Thermometers | °F range: 0 to 120°F (matched within 1/2°)°C range: -15 to 45°C
Graduations | Whole degrees
Accuracy | ±0.3°F (±0.2°C) over entire range
Slide Rules | +20 to 120°F (-10 to 60°C)
Battery life | 1000 operations with three standard "D" cells
Motor |  
Speed | 8500 rpm
Current no load | 50 Milliamperes
Type | 4.5V, direct current, permanent magnet
Weight |  
Including carrying case less batteries | 2-1/2 lbs
Shipping Weight | 3 lbs

## Mapping to external terminologies (optional)
http://vocab.nerc.ac.uk/collection/L05/current/102/
http://vocab.nerc.ac.uk/collection/L19/current/SDNKG17/
http://vocab.nerc.ac.uk/collection/P01/current/CDTASS01/1/
http://vocab.nerc.ac.uk/collection/P01/current/CDTAPS01/1/
http://vocab.nerc.ac.uk/collection/P01/current/CWETSS01/1/
http://vocab.nerc.ac.uk/collection/P10/current/GI000871/1/
http://vocab.nerc.ac.uk/collection/S04/current/S04297/1/
http://vocab.nerc.ac.uk/collection/L22/current/TOOL0080/1/

## ORCID (optional)
https://orcid.org/0000-0002-0376-5338

**Comment by danibodc** [comment]
This term has now been loaded to L22:

TOOL1753 - Industrial Instruments and Supplies Psychro-Dyne Celsius Black Organic psychrometer 

It will be live at https://vocab.nerc.ac.uk/collection/L22/current/TOOL1753 from 0730 UTC tomorrow morning.
