### ISSUE TITLE
NTR: PME miniDOT Logger (BODCNVS-1688)

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/L22#97]
Please provide the following information (all fields are mandatory unless specified otherwise)

## Device make
Precision Measurement Engineering (PME)

## Device range
miniDOT Logger

## Device model
n/a

## Model version
n/a

## Model alternative name (if applicable)
n/a

## Modification (if applicable)
n/a

## Qualification (if applicable)
n/a

## Instrument type
submersible instrument that logs dissolved oxygen and temperature measurements

## Does the tool describe a series of instruments? 
I don't think so

## Reference (if applicable)
Website: https://www.pme.com/products/minidot

## Short name
PME miniDOT

## Documentation
https://www.pme.com/products/minidot

## ORCID (optional)
0000-0002-9081-1004

**Comment by danibodc** [comment]
Hi @whshannon 

This term has now been loaded to L22 and will be live on the NVS from tomorrow morning:

TOOL1901	Precision Measurement Engineering miniDOT data logger
